### ISSUE TITLE
Use uuid or bigint for jobid?

### ISSUE THREAD

**Issue by ArcadeRenegade** [frankhommers/Hangfire.PostgreSql#100]
Hi, is it possible to use uuid or bigint for jobid?

I'm concerned that this application I am working on will reach the max size of integer jobids fairly quickly as a lot of jobs are created.

Thanks!

**Comment by ArcadeRenegade** [comment]
Hi, sorry for bugging you. Just wondering you could point me in the right direction for this, as I have a production release soon. Thanks :)

**Comment by ArcadeRenegade** [comment]
actually i just took a look at the code. job id int is coded everywhere. no big deal. i will cross the bridge of job id int overflow once / if i get to it.

**Comment by vytautask** [comment]
Hi, sorry for long wait times - very busy currently with my current affairs...
The idea would be to change `serial` type to `bigserial` column types in new `install.v11.sql` file and also change all those `Id` fields in Entities folder...

**Comment by ArcadeRenegade** [comment]
no worries. thanks!
