### ISSUE TITLE
Hangfire uses 42 connections - problem with too many clients connected

### ISSUE THREAD

**Issue by PepekT** [frankhommers/Hangfire.PostgreSql#108]
Hello,

I would like to ask if is it normal that Hanfire uses 42 connections. 

I checked some other issues, but not found solution.

If is is normal - what's the purpose of this ?

Thank you very much!

**Comment by vytautask** [comment]
Yes, that's normal. Please see https://github.com/frankhommers/Hangfire.PostgreSql/issues/85
