### ISSUE TITLE
42P01: relation does not exist (non-hangfire tables on public schema)

### ISSUE THREAD

**Issue by speige** [frankhommers/Hangfire.PostgreSql#109]
This library causes random queries that were previously working to start failing with this error. These are for actual tables that do exist. The queries are correct. It's random, because the same query will work some times & fail other times without any code changes.

Root Cause:

If you execute "SHOW search_path;" on a normal connection, it will be public (the default schema if none is specified)

However, this library seems to be executing this:
"SET  search_path TO hangfire;"

because of connection pooling, re-using an identical connection string for hangfire & non-hangfire code will randomly break non-hangfire queries unless you reset the search_path or prefix all table names with public. schema

The reproduction steps aren't 100% straightforward because it depends on concurrency & connection pooling. But, if you run a bunch of hangfire & non-hangfire queries in different concurrent threads & wait for a few minutes, the exception should occur.

Workaround:
Use a slightly different connection string for hangfire than for all other queries to disable connection pooling.

**Comment by frankhommers** [comment]
Ah, I think we could reset the search path after the install scripts have runned... As far as I can tell this is only used there.

**Comment by Tinyakov** [comment]
We also ran into this problem on our production (with PgBouncer) yesterday. 

So I made #187 for this critical issue.

**Comment by vytautask** [comment]
Thanks, @Tinyakov! 
Merged into master and pushed a new version (1.8.3) to NuGet.
