### ISSUE TITLE
Error while executing install/upgrade - Install.v11.sql

### ISSUE THREAD

**Issue by buren** [frankhommers/Hangfire.PostgreSql#111]
Thank for creating and maintaining this package!

I'm getting this exception from PostgreSQL when starting my application `Npgsql.PostgresException (0x80004005): 42601: syntax error at or near "AS"`.

Looking at the `hangfire.schema` table the `version` column is `10` and `Install.v10.sql` doesn't contain any `AS` keyword, so it must be failing on `Install.v11.sql`. The app still boots and everything seems to be working as normal (which makes sense since v11 only changes the column type).

[Line 15 in Install.v11.sql](https://github.com/frankhommers/Hangfire.PostgreSql/blob/master/src/Hangfire.PostgreSql/Install.v11.sql#L15) is what seems to cause it.

I'm using PostgreSQL 9.5.

---

Full output:

```
info: Hangfire.PostgreSql.PostgreSqlStorage[0]
      Start installing Hangfire SQL objects...
fail: Hangfire.PostgreSql.PostgreSqlStorage[0]
      Error while executing install/upgrade
Npgsql.PostgresException (0x80004005): 42601: syntax error at or near "AS"
   at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext() in C:\projects\npgsql\src\Npgsql\NpgsqlConnector.cs:line 1032
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming) in C:\projects\npgsql\src\Npgsql\NpgsqlDataReader.cs:line 444
   at Npgsql.NpgsqlDataReader.NextResult() in C:\projects\npgsql\src\Npgsql\NpgsqlDataReader.cs:line 332
   at Npgsql.NpgsqlCommand.ExecuteDbDataReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken) in C:\projects\npgsql\src\Npgsql\NpgsqlCommand.cs:line 1218
   at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken) in C:\projects\npgsql\src\Npgsql\NpgsqlCommand.cs:line 1042
   at Npgsql.NpgsqlCommand.ExecuteNonQuery() in C:\projects\npgsql\src\Npgsql\NpgsqlCommand.cs:line 1025
   at Hangfire.PostgreSql.PostgreSqlObjectsInstaller.Install(NpgsqlConnection connection, String schemaName)
info: Hangfire.PostgreSql.PostgreSqlStorage[0]
      Hangfire SQL objects installed
```

Let me know if I can provide any more information.

Thanks again.

**Comment by MaikuMori** [comment]
The problem here is that `ALTER SEQUENCE ... AS` syntax was only introduced in Postgres 10+.

Officially supported Postgres versions are `11`, `10`, `9.6`, `9.5`, `9.4`. A lot of people are still using `9.X`. For example Google Cloud SQL is using `9.6`.

**Comment by MaikuMori** [comment]
So I've dug into Postgres `9.4` [documentation ](https://www.postgresql.org/docs/9.4/sql-createsequence.html) and found this:

>Sequences are based on bigint arithmetic, so the range cannot exceed the range of an eight-byte integer (-9223372036854775808 to 9223372036854775807).

This means that to convert IDs to BIGINT you don't need to alter sequences at all since they're already based on `bigint`. So all you need to do is change the ID type.

If min required version is going to be `10` I suggest to change to [IDENTITY columns](https://www.2ndquadrant.com/en/blog/postgresql-10-identity-columns/) instead.

I do suggest that `9.4+` is supported until official EOL in November 11, 2021. Especially considering .NET demographics.

**Comment by frankhommers** [comment]
I don't think you are right (or the documentation is right). In PostgreSQL 9 the underlying datatype of an serial was integer and created the sequence automatically.

What would be a better way is to not execute the `ALTER SEQUENCE <sequencename> AS BIGINT;`  when the PostgreSQL version does not allow it. What do you think?

**Comment by MaikuMori** [comment]
You're right - data type of the column is `int` for `serial` by default. But not the sequence, you can check locally by issuing `SELECT * FROM [name of sequence]` and you'll see that max value is the same as max value of bigint. It's decoupled from the data type of the ID column.

Another [source](http://www.neilconway.org/docs/sequences/).

> What Is The Range Of Values Generated By A Sequence?
> Sequences generate 64-bit signed integers. The serial pseudotype that we used above is a 32-bit signed integer: if you want to use the full 64-bit range of the underlying sequence, use the serial8 pseudotype instead. 

It's saying the same thing. When you use serial to magically create the id and sequence, the id is created as `int`, but the underlying sequence is `bigint`.

**Comment by frankhommers** [comment]
You've convinced me ;-) This will be fixed in the next release.

**Comment by urossavelj** [comment]
Do you know when will the new version be published with this fix?

**Comment by vytautask** [comment]
It's published with v1.6.1

**Comment by vytautask** [comment]
> 
> 
> Do you know when will the new version be published with this fix?
It's published with v1.6.1

**Comment by urossavelj** [comment]
Just forgot to add it to release notes? :)

**Comment by vytautask** [comment]
> 
> 
> Just forgot to add it to release notes? :)

Yes. My bad. Had a long day ;)
