### ISSUE TITLE
Connection requires a valid client certificate

### ISSUE THREAD

**Issue by VincentVrijburg** [frankhommers/Hangfire.PostgreSql#112]
Im getting the following error trying to connect to a Google Cloud SQL (Postgres) with SSL enabled.

```
Unhandled Exception: Npgsql.PostgresException: 28000: connection requires a valid client certificate
   at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlConnector.Authenticate(String username, NpgsqlTimeout timeout, Boolean async)
   at Npgsql.NpgsqlConnector.Open(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.ConnectorPool.AllocateLong(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnection.<>c__DisplayClass32_0.<<Open>g__OpenLong|0>d.MoveNext()
```

Im using the following connection string structure:
`"Host={ipAddress};Database={dbName};Username={dbUsername};Password={dbPassword};SSL Mode=Require;TrustServerCertificate=True"`

How can I solve this issue?

**Comment by VincentVrijburg** [comment]
I ended up finding a solution to enable and use SSL encrypted connections to your PostgreSql instance.

1. Remove this project nuget package from your project.
2. Add the alternative package from @ahydrax [(Hangfire.PostgreSql.ahydrax)](https://www.nuget.org/packages/Hangfire.PostgreSql.ahydrax/)
3. Add the the `Search Path=<schema name>` parameter to your connection string and replace
`<schema name>` with the actual Hangfire schema name.

The alternative package allows you to customize the connection, including a `ClientCertificateCallback`, which we need.

4. Add the `cer` file to your project and make sure you are able to access it from code.
5. Add the `ClientCertificateCallback` to your project configuration, like so:
```csharp
config.UsePostgreSqlStorage(new DefaultConnectionBuilder(
    options.HangfireDatabaseConnectionString,
    connection =>
    {
        connection.ProvideClientCertificatesCallback += clientCerts =>
        {
            clientCerts.Add(X509Certificate.CreateFromCertFile($@"{AppDomain.CurrentDomain.BaseDirectory}\[CERT_FILENAME]"));
        };
    }));
```
6. Replace `[CERT_FILENAME]` with the actual `cer` filename.

**Feature reqeust:**
@frankhommers @vytautask It would be nice if the above was possible within this project aswell!

**Comment by frankhommers** [comment]
Can you make a PR for this @VincentVrijburg ?

**Comment by VincentVrijburg** [comment]
@frankhommers I will try to dedicate some time to a PR with a proper solution for this issue. Expect it this weekend or early next week.

**Comment by frankhommers** [comment]
@VincentVrijburg that's cool!

**Comment by VincentVrijburg** [comment]
@frankhommers I've made a PR with a proper solution to allow SSL encrypted connections. I've tested both non-SSL and SSL connections locally and they passed the Unit-tests.
