### ISSUE TITLE
Add support for DB SSL certificate

### ISSUE THREAD

**Issue by lansman** [frankhommers/Hangfire.PostgreSql#116]
I've added Hangfire 1.7.3 to ASP.NET Core app. My database (postgres) has self-signed ceritificate so i had to write some custom ceritficate check logic (**ProvideClientCertificatesCallback**, **RemoteCertificateValidationCallback** methods). I use these methods to configure Entity Framework's DbContext, i need to pass these methods to Hangfire DB configuring as well. Isn't this possible right now? Could you add such feature and provide me access to the underlying NpgsqlDbContextOptionsBuilder or similar?

```
public void ConfigureServices(IServiceCollection services)
{    
    string connectionString = "CONNECTION_STRING";
    
    services.AddDbContextPool<MyDbContext>((provider, dop) =>
    {
        dop.UseNpgsql(connectionString,
            noa =>
            {
                noa.ProvideClientCertificatesCallback(dbOptionsReader.AddSslCertificate);
                noa.RemoteCertificateValidationCallback(dbOptionsReader.VerifySslManually);                
            });
    });

    services.AddHangfire((provider, config) =>
    {
        config.UsePostgreSqlStorage(connectionString);

        // how to set ProvideClientCertificatesCallback and RemoteCertificateValidationCallback ??
    });
}
```

**Comment by frankhommers** [comment]
This is possible. I am pretty sure a PR of @VincentVrijburg made this possible. Maybe he can explain here?

**Comment by VincentVrijburg** [comment]
@frankhommers @lansman I will create a Wiki page for it soon. In the mean time, have a look at this issue where I stated an example #112
