### ISSUE TITLE
System.ObjectDisposedException: 'Cannot access a disposed object. Object name: 'NpgsqlConnection'.'

### ISSUE THREAD

**Issue by urossavelj** [frankhommers/Hangfire.PostgreSql#122]
We were using this code block below to get all queued jobs and processing jobs and delete them in version 1.6.0 and it was working fine also before this version for a long time. Today updated to the latest version 1.6.1 to solve #111 but now it breaks on the line under the second comment with the following error:

>System.ObjectDisposedException: 'Cannot access a disposed object. Object name: 'NpgsqlConnection'.'

Have you made any breaking changes to IMonitoringApi or anything connected with it?

```c#
public static void PurgeJobs(this IMonitoringApi monitor)
        {
            const int count = 1000;
            var toDelete = new List<string>();

            // Mark queued jobs for deletion
            foreach (var queue in monitor.Queues())
            {
                for (var i = 0; i < Math.Ceiling(queue.Length / 1000d); i++)
                {
                    monitor.EnqueuedJobs(queue.Name, 1000 * i, count).ForEach(x => toDelete.Add(x.Key));
                }
            }

            // Mark processing jobs for deletion
            for (var i = 0; i < Math.Ceiling(monitor.ProcessingCount() / 1000d); i++)
            {
                monitor.ProcessingJobs(1000*i, count).ForEach(x => toDelete.Add(x.Key));
            }

            foreach (var jobId in toDelete)
            {
                BackgroundJob.Delete(jobId);
            }
        }
```

**Comment by vytautask** [comment]
Hm. Do not remember changing anything related to that. Maybe you have a stacktrace/more localized exception trace?

Vytautas Kasparavičius

**Comment by haacked** [comment]
The same thing happens to me when I try to use to use `HangFire.PostgreSql` version `1.6.1` and visit `https://localhost:5001/hangfire`.

I downgraded to `1.6.0` and the dashboard works fine. Something definitely changed in `1.6.1` to break things.

Full stacktrace below:

<details>
ObjectDisposedException: Cannot access a disposed object. Object name: 'NpgsqlConnection'.
Npgsql.NpgsqlConnection.CheckDisposed() in C:\projects\npgsql\src\Npgsql\NpgsqlConnection.cs
Npgsql.NpgsqlConnection.CreateCommand() in C:\projects\npgsql\src\Npgsql\NpgsqlConnection.cs
Npgsql.NpgsqlConnection.CreateDbCommand() in C:\projects\npgsql\src\Npgsql\NpgsqlConnection.cs
System.Data.Common.DbConnection.System.Data.IDbConnection.CreateCommand()
Dapper.CommandDefinition.SetupCommand(IDbConnection cnn, Action<IDbCommand, object> paramReader) in C:\projects\dapper\Dapper\CommandDefinition.cs
Dapper.SqlMapper.QueryImpl<T>(IDbConnection cnn, CommandDefinition command, Type effectiveType)+MoveNext() in C:\projects\dapper\Dapper\SqlMapper.cs
System.Collections.Generic.List<T>.AddEnumerable(IEnumerable<T> enumerable)
System.Collections.Generic.List<T>..ctor(IEnumerable<T> collection)
System.Linq.Enumerable.ToList<TSource>(IEnumerable<TSource> source)
Dapper.SqlMapper.Query<T>(IDbConnection cnn, string sql, object param, IDbTransaction transaction, bool buffered, Nullable<int> commandTimeout, Nullable<CommandType> commandType) in C:\projects\dapper\Dapper\SqlMapper.cs
Dapper.SqlMapper.Query(IDbConnection cnn, string sql, object param, IDbTransaction transaction, bool buffered, Nullable<int> commandTimeout, Nullable<CommandType> commandType) in C:\projects\dapper\Dapper\SqlMapper.cs
Hangfire.PostgreSql.PostgreSqlMonitoringApi.GetTimelineStats(NpgsqlConnection connection, IDictionary<string, DateTime> keyMaps)
Hangfire.PostgreSql.PostgreSqlMonitoringApi.GetHourlyTimelineStats(NpgsqlConnection connection, string type)
Hangfire.PostgreSql.PostgreSqlMonitoringApi.<HourlyFailedJobs>b__21_0(NpgsqlConnection connection)
Hangfire.PostgreSql.PostgreSqlMonitoringApi.UseConnection<T>(Func<NpgsqlConnection, T> action)
Hangfire.PostgreSql.PostgreSqlMonitoringApi.HourlyFailedJobs()
Hangfire.Dashboard.Pages.HomePage.Execute()
Hangfire.Dashboard.RazorPage.TransformText(string body)
Hangfire.Dashboard.RazorPage.ToString()
Hangfire.Dashboard.RazorPageDispatcher.Dispatch(DashboardContext context)
Hangfire.Dashboard.AspNetCoreDashboardMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
</details>

**Comment by vytautask** [comment]
Found the culprit. Some strange using statement for an object which was created elsewhere.
Will publish a fix in a few minutes.

**Comment by vytautask** [comment]
🎉  Fixed in 1.6.2 and published to NuGet. Should be indexed and appear in results in the near future.
Thanks for all the help, guys! 🙇

**Comment by haacked** [comment]
New version works for me. Thanks!

**Comment by urossavelj** [comment]
Works also for me, thank you @vytautask :)

**Comment by ddo88** [comment]
thank upgrade works for me
