### ISSUE TITLE
A non-blocking socket operation could not be completed immediately

### ISSUE THREAD

**Issue by joelnotified** [frankhommers/Hangfire.PostgreSql#123]
After updating my project to ASP.NET Core 2.2 (from 2.1) I started getting errors when setting up Hangfire.

This is the code that throws the error:
`services.AddHangfire(config => config.UsePostgreSqlStorage(connectionString));`

And this is the error:
```
System.Net.Internals.SocketExceptionFactory.ExtendedSocketException
  HResult=0x80004005
  Message=A non-blocking socket operation could not be completed immediately [::1]:5432
  Source=System.Net.Sockets
  StackTrace:
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at Npgsql.NpgsqlConnector.Connect(NpgsqlTimeout timeout) in C:\projects\npgsql\src\Npgsql\NpgsqlConnector.cs:line 692
```

I'm using:
`Hangfire.AspNetCore version 1.7.6 `
`Hangfire.PostgreSql version 1.6.2`
`Npgsql version 4.0.7`

I received similar errors in my own code that opens connections to the database, I solved it by changing from `NpgsqlConnection.Open()` to `NpgsqlConnection.OpenAsync()`. I don't know if it could be related to something similar?

**Comment by vytautask** [comment]
Please update to 1.6.3 and see if issue persists (we've had some problems with socket exhaustion).

**Comment by joelnotified** [comment]
That didn't seem to help unfortunately. What would help to debug this issue?

![image](https://user-images.githubusercontent.com/27775157/64324128-0ec86880-cfc6-11e9-9e43-416e641664b4.png)

```
 	[External Code]	
 	Npgsql.dll!Npgsql.NpgsqlConnector.Connect(Npgsql.NpgsqlTimeout timeout) Line 692	C#
 	Npgsql.dll!Npgsql.NpgsqlConnector.RawOpen(Npgsql.NpgsqlTimeout timeout, bool async, System.Threading.CancellationToken cancellationToken) Line 555	C#
 	Npgsql.dll!Npgsql.NpgsqlConnector.Open(Npgsql.NpgsqlTimeout timeout, bool async, System.Threading.CancellationToken cancellationToken) Line 413	C#
 	Npgsql.dll!Npgsql.ConnectorPool.AllocateLong(Npgsql.NpgsqlConnection conn, Npgsql.NpgsqlTimeout timeout, bool async, System.Threading.CancellationToken cancellationToken) Line 246	C#
 	Npgsql.dll!Npgsql.NpgsqlConnection.Open.__OpenLong|0() Line 305	C#
 	[External Code]	
 	Npgsql.dll!Npgsql.NpgsqlConnection.Open(bool async, System.Threading.CancellationToken cancellationToken) Line 229	C#
 	Npgsql.dll!Npgsql.NpgsqlConnection.Open() Line 153	C#
 	[External Code]	
...
```

**Comment by frankhommers** [comment]
I am unsure it's a problem of this tool.
Does it help if you do this: https://github.com/npgsql/npgsql/issues/1183#issuecomment-230179072
