### ISSUE TITLE
can i use CST (China Standard Time UTC+8:00)

### ISSUE THREAD

**Issue by qiang999** [frankhommers/Hangfire.PostgreSql#128]
I use Hangfire.PostgreSQl，have a question:
I found storage time is UTC.
My server's time is CTS.

hangfire.postgresql code:
 string query =
				$@"UPDATE ""{_options.SchemaName}"".""server"" 
				SET ""lastheartbeat"" = NOW() AT TIME ZONE 'UTC' 
				WHERE ""id"" = @id;";

can i use CST (China Standard Time UTC+8:00)

**Comment by frankhommers** [comment]
Sure. Only the heartbeat is registered in UTC. Everything else should just work.
