### ISSUE TITLE
Next execution shows a time in the past, and next shows N/A

### ISSUE THREAD

**Issue by ofirgeller** [frankhommers/Hangfire.PostgreSql#13]
after the first time a cron task is run I see this in the dashboard and the task will never run again.

**Comment by bherila** [comment]
Agree this is an issue. It might be a problem with Hangfire itself. Please send a PR if you need this fixed or point to the relevant commit on Github so we can merge it.

**Comment by vytautask** [comment]
@ofirgeller is this still an issue?

**Comment by ofirgeller** [comment]
I don't know. it has been a while.
