### ISSUE TITLE
troubleshoot connection timeout

### ISSUE THREAD

**Issue by towts** [frankhommers/Hangfire.PostgreSql#14]
Having a slight issue getting started. 
Dashboard loads proper on initial run but errors out on page refresh or trying to navigate the top bar options. I've enabled owin error page. The error is

Exception: Timeout while getting a connection from pool.
Npgsql.NpgsqlConnectorPool.RequestConnector(NpgsqlConnection Connection)

I've tried my local connection string as well as our staging one.
The hangfire schema and tables get created. Not sure why the pool request timeout on page refresh etc. Hoping for some suggestions.

**Comment by towts** [comment]
Updated code to as per stackoverflow suggest

http://stackoverflow.com/questions/28202608/timeout-while-getting-a-connection-from-pool-hangfire-postgres


 var sb =
                new NpgsqlConnectionStringBuilder(ConfigurationManager.ConnectionStrings["pgsql-db"].ConnectionString)
                {
                    Pooling = false
                };

            var storage = new PostgreSqlStorage(sb.ConnectionString);
            
            Hangfire.GlobalConfiguration.Configuration.UseStorage(storage);

**Comment by bherila** [comment]
This fixes the error for me. Alternatively, put `;Pooling=false` in your connection string manually.
