### ISSUE TITLE
Cancellation token immediately throws  Hangfire.Server.JobAbortedException: 'The operation was canceled.'

### ISSUE THREAD

**Issue by cristianbodnar** [frankhommers/Hangfire.PostgreSql#142]
I'm trying to use IJobCancellationToken (which works with a MongoDB implementation) and PostgreSQL, but after the job starts, it immediately throw Hangfire.Server.JobAbortedException: 'The operation was canceled.'  error when checking with: 
                cancellationToken.ThrowIfCancellationRequested();
Any idea how to fix this?

**Comment by cristianbodnar** [comment]
If I use CancellationToken, I get System.OperationCanceledException: 'The operation was canceled.'

**Comment by frankhommers** [comment]
Isn't this as designed? Can you elaborate more on what you're doing?

**Comment by frankhommers** [comment]
No response...
