### ISSUE TITLE
Stored jobs date/count limit

### ISSUE THREAD

**Issue by PavelJM** [frankhommers/Hangfire.PostgreSql#143]
It looks like jobs are automatically deleted from the database after 24 hours.
Is that correct and is there some way how to set this limit?

**Comment by walizada** [comment]
This is what I use to accomplish this:

```
 public class ProlongExpirationTimeAttribute : JobFilterAttribute, IApplyStateFilter
    {
        public void OnStateApplied(ApplyStateContext context, IWriteOnlyTransaction transaction)
        {
            context.JobExpirationTimeout = TimeSpan.FromDays(30 * 3);
        }

        public void OnStateUnapplied(ApplyStateContext context, IWriteOnlyTransaction transaction)
        {
            context.JobExpirationTimeout = TimeSpan.FromDays(30 * 3);
        }
    }

```
And add this filter to the GlobalJobFilter where ever you are initializing Hangfire:


  `GlobalJobFilters.Filters.Add(new ProlongExpirationTimeAttribute());`

**Comment by PavelJM** [comment]
@walizada: Thank you very much, that solved my problem. If it can be helpful for someone - I found out that job deletions are implemented in the ExpirationManager.cs. There is a list of "managed" tables specified in this class. Records from these tables are deleted according to the expiration date ("expireat" column). So you are right,  this shouldn't be related to the particular storage as long as each storage respects and implements the same condition for deleting records.
