### ISSUE TITLE
IGlobalConfiguration in PostgreSqlBootstrapperConfigurationExtensions

### ISSUE THREAD

**Issue by Sephit** [frankhommers/Hangfire.PostgreSql#145]
Changing 
`public static PostgreSqlStorage UsePostgreSqlStorage`
to
`public static IGlobalConfiguration<PostgreSqlStorage> UsePostgreSqlStorage`

enables you to fluently add new extensions on hangfire

**Comment by vytautask** [comment]
I've added it with f4cff7743e5e867160da88dc8509ed544defa51d into special feature branch 1.7.0

**Comment by vytautask** [comment]
Released in 1.7.0
