### ISSUE TITLE
Periodically commit commands.

### ISSUE THREAD

**Issue by arsen1991** [frankhommers/Hangfire.PostgreSql#146]
The application periodically runs commit commands so we see multiple transactions by Hangfire.PostgreSql and we are getting huge log file. Is it normal behavior. How can we decrease the intensity of such queries. We decreased the connection max pool but I don't know if it's the right solution.

**Comment by vytautask** [comment]
It's hard to see what's the problem from my perspective.
Is this text log or is this database log? One could be improved by using filters, another one should never be a problem in the first place...

**Comment by Frazi1** [comment]
Try using a higher log level for Hangfire. If you are on .NET Core and rely on Microsoft's `ILogger` interface, see this article for example: https://docs.hangfire.io/en/latest/configuration/configuring-logging.html#net-core-and-asp-net-core

If you use some other logging framework, reference its documentation.

Try switching to `Warning` or `Error` log level. It should decrease the number of log messages you get.
