### ISSUE TITLE
Automatic PosgreSql cleanup for successful jobs

### ISSUE THREAD

**Issue by jayasurya-jeyakodi** [frankhommers/Hangfire.PostgreSql#149]
Is there any way to configure probably in PostgreStorageOptions to automatically delete succeeded jobs, I believe this feature exists for SqlServer.

**Comment by frankhommers** [comment]
Can you point to the SqlServer feature source code?

**Comment by hoppel** [comment]
https://github.com/HangfireIO/Hangfire/blob/master/src/Hangfire.SqlServer/SqlServerStorageOptions.cs#L40
https://github.com/HangfireIO/Hangfire/blob/c4bdc668dc898c9c057372e344ffad701765d788/src/Hangfire.SqlServer/ExpirationManager.cs

**Comment by Plasma** [comment]
I think this feature has been implemented.

**Comment by azygis** [comment]
The feature is indeed implemented, the options value is just a different name: `JobExpirationCheckInterval`.
