### ISSUE TITLE
No manual installation of Schema.

### ISSUE THREAD

**Issue by adamcarr1976** [frankhommers/Hangfire.PostgreSql#151]
Our production systems require a database admin to make any schema changes to the database.  Is there any standalone scripts that can be used to install the schema.

I would uncomfortable to give the application permissions to make schema changes even when we didn't have this security requirement.

**Comment by frankhommers** [comment]
Run these scripts: in order: https://github.com/frankhommers/Hangfire.PostgreSql/tree/master/src/Hangfire.PostgreSql/Scripts
