### ISSUE TITLE
I there is any way to start supporting CockroachDB?

### ISSUE THREAD

**Issue by sergeyshaykhullin** [frankhommers/Hangfire.PostgreSql#152]
I tried to start Hangfire with PostgreSQL storage on CockroachDB, but got some problems:
- CockroachDB is not supporting schema and using cross-database queries
- Do not support anonymous code block with `DO $$`
- This fork is not complaining on schema creating (because there no schema creation), but migrations code is 2 years old https://github.com/ahydrax/Hangfire.PostgreSql/blob/master/src/Hangfire.PostgreSql/Schema/Install.v3.sql

**Comment by frankhommers** [comment]
I do not know about CoachroachDB. I think it's just using the PG protocol and nothing else.
I would recommend to fork this and build Hangfire.CockroachDB. I think it's too much of a niche for us to support this.

**Comment by frankhommers** [comment]
It's also still beta: https://www.cockroachlabs.com/docs/stable/build-a-csharp-app-with-cockroachdb.html#before-you-begin
