### ISSUE TITLE
JobStorage.Current property value has not been initialized Error Message

### ISSUE THREAD

**Issue by Tieantono** [frankhommers/Hangfire.PostgreSql#155]
Hi, I'm using ASP.NET Core 3.1 (with Blazor) `Hangfire.Core 1.7.11`, `Hangfire.AspNetCore 1.7.11`, and `Hangfire.PostgreSql 1.7.0` packages, and I've followed the README documentation how to use this data storage package.

In my `ConfigureServices` method:
```csharp
services.AddHangfire(configuration =>
{
    configuration.SetDataCompatibilityLevel(CompatibilityLevel.Version_170);
    configuration.UseSimpleAssemblyNameTypeSerializer();
    configuration.UseRecommendedSerializerSettings();
    configuration.UsePostgreSqlStorage(Configuration.GetConnectionString("OpsHfDb"));
});
```
In my `Configure` method:
```csharp
app.UseHangfireServer();
app.UseHangfireDashboard("/hangfire", new DashboardOptions
{
    Authorization = new []
    {
        new HfDashboardFilter()
    }
});
```
But whenever I start my web app, the application stop and this error message always show up:
```
System.InvalidOperationException: JobStorage.Current property value has not been initialized. You must set it before using Hangfire Client or Server API.
```
The above problem can be solved by add this following code:
```csharp
JobStorage.Current = new PostgreSqlStorage(Configuration.GetConnectionString("OpsHfDb"));
```
Do I really need to use the above code too?

I also have a question regarding the idle state sessions when using this package. My Postgres connection always used up to 20 connections when my app running using this data storage, is that normal?

Thanks in advance.

EDIT:
Fixed connection string property name typo from "HfDb" to "OpsHfDb" on the first snippet.

**Comment by KhorAMus** [comment]
@Tieantono  Why in one place you used "HfDb" but in the next place you used "OpsHfDb"?

**Comment by doylemark** [comment]
Did you ever resolve this problem? @Tieantono

**Comment by Tieantono** [comment]
> Did you ever resolve this problem? @Tieantono

I haven't try other configuration, even on my new project, so I'm still using the above codes to make it work.

**Comment by azygis** [comment]
It feels like `HfDashboardFilter` is using `JobStorage.Current` in the constructor, at which point the storage is indeed not set up yet.

In the latest versions of hangfire, `UseHangfireServer` middleware is deprecated in favor of just plain service registrations.

Regarding idle connections - yes, that is normal, to increase performance by not opening new physical connections, by default the Npgsql library has internal connection pool. You can make certain configurations (like min/max pool size) using [connection string parameters](https://www.npgsql.org/doc/connection-string-parameters.html#pooling).

**Comment by azygis** [comment]
Closing the issue. Feel free to reopen it if you need help investigating more.

As said in the last comment, it looks like something somewhere tries to access `JobStorage.Current` before the configuration/startup has been fully completed.

**Comment by DmitrySikorsky** [comment]
So, with the version 1.7.30 if I initialize Hangfire like this:

```
services.AddHangfire(c => c.UseSqlServerStorage(configuration.GetConnectionString("Default")));
services.AddHangfireServer();
```

and then try to call, for example, `RecurringJob.AddOrUpdate` in the `Configure` method, I will have exception from the issue title. I didn't have it locally, because locally I have development environment, and `applicationBuilder.UseHangfireDashboard()` is called. If this method is called before, `RecurringJob.AddOrUpdate` will work without any problem.

Another way is to inject the `IBackgroundJobClient` (or get it from the IServiceProvider, it is not important) before calling `RecurringJob.AddOrUpdate`. You don't need to do anything with the `IBackgroundJobClient` instance, just inject it. After that everything works. I hope it will save time for someone.
