### ISSUE TITLE
Windows defender detects trojan in 1.7.0

### ISSUE THREAD

**Issue by jhartmann123** [frankhommers/Hangfire.PostgreSql#157]
Hi,

we've just started with a new project which uses Hangfire.Postgres 1.7.0.

On multiple (3) developer machines Windows Defender detects a trojan in the lib as soon as it gets downloaded from nuget.

We do not get any warnings when we recompile the library from source (using `build.ps1`), neither in the debug nor the release version.

![image](https://user-images.githubusercontent.com/20248188/86894739-c6a53580-c103-11ea-80ce-241edd55bd2b.png)

Not seeing any comments about that since release, I hope it's just a false positive with the latest defender updates...

**Comment by vytautask** [comment]
That's strange. [According to VirusTotal](https://www.virustotal.com/gui/file/9bd5d0f0a2018ea6960b3137040f259c4da43f15b5c619ad0e9830202b7b282a/detection), only MS Defender flags it down with this issue. In ["relations" tab the dll says 0/70 detections](https://www.virustotal.com/gui/file/9bd5d0f0a2018ea6960b3137040f259c4da43f15b5c619ad0e9830202b7b282a/relations).
Also, if I unpack the nuget package and scan DLL directly, [it does not detect anything](https://www.virustotal.com/gui/file/ac85855b067eab15e4070db97d2b86f9e59bb1c932b476ed5c6a0cf9e2264893/detection).
Also filed [incorrect detection form in MS](https://www.microsoft.com/en-us/wdsi/submission/ead30eab-14dc-430b-93b2-3857699774d4). Not sure that will help...

**Comment by emreyigit** [comment]
faced with same issue on 1.7.0

**Comment by vytautask** [comment]
>We do not get any warnings when we recompile the library from source (using build.ps1), neither in the debug nor the release version.
I recreated a package on completely another PC and the problem persist - Microsoft detects it as a trojan "Trojan:Win32/Fuery.C!cl".
Seems like MS released some crappy virus definitions lately and [I expect they will fix it soon](https://developercommunity.visualstudio.com/content/problem/1046937/windows-defender-reports-a-trojan-1.html).

**Comment by vytautask** [comment]
Today [virus total does not find any issues with any antivirus software](https://www.virustotal.com/gui/file/9bd5d0f0a2018ea6960b3137040f259c4da43f15b5c619ad0e9830202b7b282a/detection) on the same package. I guess Microsoft fixed their issues and should be OK now everywhere (antivirus definitions update might be needed sometimes).

**Comment by jhartmann123** [comment]
I can confirm that it works with the latest defender update. Thanks for your help!
