### ISSUE TITLE
Upgrade NpgSql to v3

### ISSUE THREAD

**Issue by kieranbenton** [frankhommers/Hangfire.PostgreSql#16]
Hi,
I'm trying to keep up-to-date with NpgSql as there's great reasons to use some of its new features in the v3 branch (core support if nothing else), but Hangfire.PostgreSql is incompatible with it.

Any chance you could upgrade your packages and fix the probably relatively minor issues blocking this?

Cheers.

**Comment by zsims** [comment]
Raised a PR, we also need npgsql 3 :)
