### ISSUE TITLE
Support custom table prefix

### ISSUE THREAD

**Issue by Salgat** [frankhommers/Hangfire.PostgreSql#165]
[Hangfire.Pro.Redis](https://www.hangfire.io/pro/#hangfireproredis) supports a RedisStorageOptions.Prefix property that allows for isolating/namespacing Hangfire. This allows a single Redis persistence to support an unlimited number of isolated "hangfire environments". This is useful because it means that many unrelated services can share the same Redis for their own job scheduling.

Adding the same option to this library would accomplish the same thing, allowing one SQL server to support many isolated and independent job schedulers/processors. To note, you can sort of accomplish something similar using some magic with queues (see [here](https://earwicker.com/Hangfire_A_Tale_of_Several_Queues.html)), but the problem with this is that **all** hangfire processors still have to be able to deserialize the job even if it won't run the job locally, which limits its use.

**Comment by frankhommers** [comment]
We have this in the form of a customizable schema. 

https://github.com/frankhommers/Hangfire.PostgreSql/blob/5d5cf560613f0c588c82267dffdb00fecd3cd61c/src/Hangfire.PostgreSql/PostgreSqlStorageOptions.cs#L86

**Comment by Salgat** [comment]
This seems to work great, thank you so much!
