### ISSUE TITLE
PostgreSqlConnection.Heartbeat() should throw a BackgroundServerGoneException when no servers exist to update.

### ISSUE THREAD

**Issue by AlexaLempel** [frankhommers/Hangfire.PostgreSql#167]
As of Hangfire version 1.7.0, the storage [`Heartbeat` method ](https://github.com/frankhommers/Hangfire.PostgreSql/blob/5e545e5ae2fa1fe1a0e7a8a51fe97c6d1ce56b9f/src/Hangfire.PostgreSql/PostgreSqlConnection.cs#L410) should throw a `BackgroundServerGoneException` when no servers respond to heartbeat, in order to allow [Hangfire.Server.ServerHeartbeatProcess to automatically restart failed servers](https://github.com/HangfireIO/Hangfire/blob/b5fabd9e544bdfcbf4eabfb8bde33ba1e30ac4d1/src/Hangfire.Core/Server/ServerHeartbeatProcess.cs#L65).

This should fix a known [issue with servers disappearing](https://github.com/HangfireIO/Hangfire/issues/1123), which has occurred in my app that's using Hangfire.PostgreSql v1.7.1.

See [Hangfire.SqlServer `SqlServerConnection.HeartBeat()`](https://github.com/HangfireIO/Hangfire/blob/b5fabd9e544bdfcbf4eabfb8bde33ba1e30ac4d1/src/Hangfire.SqlServer/SqlServerConnection.cs#L483) for example of how `PostgreSqlConnection.Heartbeat()` should be updated.

**Comment by frankhommers** [comment]
Are you able to put this in a PR?

**Comment by AlexaLempel** [comment]
Sure, will do

**Comment by AlexaLempel** [comment]
Sorry, didn't get a chance to do this in as timely a manner as I'd hoped. Frazi1's PR #181 looks good to me though, and should fix the issue. https://github.com/frankhommers/Hangfire.PostgreSql/pull/181/commits/0449308e2ed6fe4151bcaab6463c41e771a2b532

**Comment by AlexaLempel** [comment]
Should be fixed by PR #181
