### ISSUE TITLE
Is Hangfire.PostgreSql still maintained?

### ISSUE THREAD

**Issue by zsims** [frankhommers/Hangfire.PostgreSql#18]
Firstly, thanks for the extension to Hangfire.

This hasn't had any updates in almost a year, is it still maintained?

**Comment by bherila** [comment]
:frowning:

**Comment by frankhommers** [comment]
I will continue it in the near future. But for now I'm busy on other projects that don't need Hangfire.

**Comment by zsims** [comment]
No worries, thanks for the great library regardless. Any chance of a TODO or some issues/tasks? Reading the code there were obviously a few plans (distributed locks etc)

**Comment by bherila** [comment]
I just found this library 2 days ago and since then have got it up and running. Auto installation of the db schema didn't work but I was able to run the included install scripts manually. From there on the majority of functionality seems to be working fine.

**Comment by bherila** [comment]
Looks like a bunch of PRs just got merged! Thanks @frankhommers again and I hope to be able to contribute soon :smile:
