### ISSUE TITLE
even though ids are bigint, the max shows 2 billion as if it's a 32-bit int

### ISSUE THREAD

**Issue by kbrichan** [frankhommers/Hangfire.PostgreSql#182]
Install.v11.sql changed ids to bigint. But the max value is still 2^31 - 1 as shown in the sequence properties.
![image](https://user-images.githubusercontent.com/3181394/104664269-0a1cc580-568c-11eb-9c95-0ba18d0c1a20.png)
When I attempt to increase the Maximum in this dialog, it says "out of range for sequence data type integer".
Am I missing something?

**Comment by frankhommers** [comment]
With what tool are you viewing this?

**Comment by frankhommers** [comment]
You are right. The datatype of the column is update, but the datatype of the sequence was not. We have to fix this.

**Comment by kbrichan** [comment]
Thank you. In the meantime, what would the SQL script look like to alter the sequence? The pgAdmin 4 tool I'm using doesn't allow me to change the max.

**Comment by frankhommers** [comment]
I would drop the sequence and recreate it with the other type. The exact SQL, I don't know.

**Comment by kbrichan** [comment]
fyi: here is a sample SQL to alter a sequence
alter sequence hangfire.job_id_seq as bigint;
this automatically adjusts the maximum to 2^64-1 -- do not need to drop the sequence and recreate it

**Comment by frankhommers** [comment]
Thx! Great!
