### ISSUE TITLE
How to make a queue exclusive to a set service instances for both processing jobs and related monitoring?

### ISSUE THREAD

**Issue by natalie-perret-1986** [frankhommers/Hangfire.PostgreSql#185]
I would like to know, given a queue `queueName`, how can I make it exclusively available for processing its jobs and the related monitoring to **only** a set of service instances,

About the way to define that a job can be processed with a limit of only one single job for all the servers connected to the same queue, I ended up doing:
```csharp
jobServerOptions.WorkerCount = 1
jobServerOptions.Queues = new [] { queueName }
```
I think this should prevent other instances that do not have the same values to process the jobs that are in this queue, right?

Now my issue is more about the Hangfire Dashboard, cause it keeps showing jobs that are not exclusive to the given queue I just assigned early on. How can I achieve that?

**Comment by frankhommers** [comment]
Isn't this a question which needs to be directed at Hangfire itself and not the storage provider?

**Comment by vytautask** [comment]
Stale and seems like provider issue

**Comment by natalie-perret-1986** [comment]
An example would be appreciated. tho
