### ISSUE TITLE
Job enqueued for hours

### ISSUE THREAD

**Issue by DanBrk** [frankhommers/Hangfire.PostgreSql#186]
I am running few scheduled recurring jobs and the jobs are enqueued and remain in queue for a long time. The processing state occurs with latency of 1 to 4 hours.
I am using .net core with .NET 5 runtime, Hangfire 1.7.19, PostgreSQL Server 1.8.2.
Please advise why it is happening.
Thanks.

**The job remains in enqueued state:**
![snip_20210315](https://user-images.githubusercontent.com/48959452/111120807-804a8500-8574-11eb-91d8-e715d8e4a87b.png)

**After the job processing:**
![snip_20210315-1](https://user-images.githubusercontent.com/48959452/111120988-c0aa0300-8574-11eb-8111-aa8e7d4e3eef.png)

**Comment by rosenbjerg** [comment]
Looks like same problem we are facing in #161

**Comment by vytautask** [comment]
Probably is solved with 1.8.4 release. Please check.

**Comment by DanBrk** [comment]
1.8.4 release solved the issue for me. Thanks
