### ISSUE TITLE
Hangfire .net core postgresql tables not created

### ISSUE THREAD

**Issue by AdemAygun** [frankhommers/Hangfire.PostgreSql#190]
I created a .net project in .net core 5.0 according to this [link ](https://dev.to/gmarokov/getting-started-with-hangfire-on-asp-net-core-and-postgresql-on-docker-56ak)and run these commands
`dotnet ef migrations add InitContext && dotnet ef database update`
but it seems no affected to migration
```
public partial class InitContext : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
        }
        protected override void Down(MigrationBuilder migrationBuilder)
        {
        }
    }
```

Finally I get error ***relation hangfire.job does not exist*** when I performed `dotnet run`

**Comment by AdemAygun** [comment]
My Postgres user was not permitted. But there was no error about "permission denied" or anything

**Comment by frankhommers** [comment]
You need to have a database and a user on that database with enough rights to create all the tables.
