### ISSUE TITLE
Update counter_id_seq, hash_id_seq, jobparameter_id_seq, jobqueue_id_seq, hangfire.list_id_seq, set_id_seq, state_id_seq to use bigint as well

### ISSUE THREAD

**Issue by kbrichan** [frankhommers/Hangfire.PostgreSql#192]
case 182 was for doing an upgrade script to change 8 sequences from int to bigint
the commit 6e37c50 for case 182 only changed one of them (job_id_seq)
it should have changed all 8: job_id_seq, counter_id_seq, hash_id_seq, jobparameter_id_seq, jobqueue_id_seq, hangfire.list_id_seq, set_id_seq, state_id_seq

**Comment by frankhommers** [comment]
Please supply a pull request.

**Comment by kbrichan** [comment]
I'm confused. This new case was merely commenting on the work you did to address case 182. I'm not currently a contributing developer for this project. Are you saying the way case 182 will be fully addressed is by me fixing it?

**Comment by vytautask** [comment]
> 
> 
> I'm confused. This new case was merely commenting on the work you did to address case 182. I'm not currently a contributing developer for this project. Are you saying the way case 182 will be fully addressed is by me fixing it?

Well, this is not commercially backed open source project without any enterprise entity behind it. Everyone is welcome to create PRs for it. Especially if you want your changes to be done at a rapid pace.

**Comment by azygis** [comment]
Issue has been resolved internally, release is pending.
