### ISSUE TITLE
Enable JobExpirationCheckInterval Setting

### ISSUE THREAD

**Issue by cescobargiraldo** [frankhommers/Hangfire.PostgreSql#193]
Right now the PostgreSqlStorage.cs is creating the ExpirationManager without passing down the checkInterval as a parameter:

![image](https://user-images.githubusercontent.com/25250963/119054833-88b0a900-b985-11eb-8daf-f7fd31d816e4.png)

Making the ExpirationManager use the default value of 1 hour. Shouldn't this PostgreSqlStorage.cs have this as a configurable option like the SqlServerStorage.cs does?

![image](https://user-images.githubusercontent.com/25250963/119055013-cca3ae00-b985-11eb-9c4d-49dbd5a2a006.png)

**Comment by cescobargiraldo** [comment]
@frankhommers - Is this the right channel to bring this to your attention?

**Comment by vytautask** [comment]
Should be fixed with 1.8.6
