### ISSUE TITLE
MAXVALUE (9223372036854775807) is out of range for sequence data type integer

### ISSUE THREAD

**Issue by jblackwood12** [frankhommers/Hangfire.PostgreSql#195]
I am using this version: "**PostgreSQL 11.6 on x86_64-pc-linux-musl, compiled by gcc (Alpine 9.2.0) 9.2.0, 64-bit**"

I think the change yesterday to the [sql script](https://github.com/frankhommers/Hangfire.PostgreSql/blob/master/src/Hangfire.PostgreSql/Scripts/Install.v14.sql), to make it compatible with Postgres 9.6 caused this issue.

Here's the error I receive:

`
13:33:48 [Information] - MESSAGE: Start installing Hangfire SQL objects...
13:33:49 [Error] - MESSAGE: Error while executing install/upgrade
Npgsql.PostgresException (0x80004005): 22023: MAXVALUE (9223372036854775807) is out of range for sequence data type integer
   at Npgsql.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|194_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery()
   at Hangfire.PostgreSql.PostgreSqlObjectsInstaller.Install(NpgsqlConnection connection, String schemaName)
  Exception data:
    Severity: ERROR
    SqlState: 22023
    MessageText: MAXVALUE (9223372036854775807) is out of range for sequence data type integer
    File: sequence.c
    Line: 1460
    Routine: init_params
13:33:49 [Information] - MESSAGE: Hangfire SQL objects installed.
`

**Comment by jblackwood12** [comment]
I think this might be a solution that could work:
https://stackoverflow.com/a/64940394

So the code in that script referenced above could be:
`ALTER SEQUENCE job_id_seq as bigint MAXVALUE 9223372036854775807;`

**Comment by alexrosenfeld10** [comment]
I am getting this as well after upgrading to the latest version (released today). @frankhommers is there a manual step needed here? Perhaps a bug in the install script?

**Comment by vytautask** [comment]
Seems that the change is not compatible with newer postresql versions.

**Comment by jblackwood12** [comment]
> I am getting this as well after upgrading to the latest version (released today). @frankhommers is there a manual step needed here? Perhaps a bug in the install script?

Yes it's from this script that was changed yesterday: https://github.com/frankhommers/Hangfire.PostgreSql/blob/master/src/Hangfire.PostgreSql/Scripts/Install.v14.sql

**Comment by alexrosenfeld10** [comment]
I opened https://github.com/frankhommers/Hangfire.PostgreSql/pull/196 for this. @vytautask

**Comment by vytautask** [comment]
Please update to version 1.8.5.1 and let me know if this fixes the issue.

**Comment by frankhommers** [comment]
Hmmm, I need to test on olders pg's as well I guess.... Sorry for the inconvenience @vytautask !

**Comment by alexrosenfeld10** [comment]
seems good to me, thx

**Comment by vytautask** [comment]
No worries. We have those appveyor tests running on master branch. They seem to catch at least this defficiency.

**Comment by rbrugnollo** [comment]
> Please update to version 1.8.5.1 and let me know if this fixes the issue.

1.8.5.1 solved the issue for me. Thanks!

**Comment by LuccaPrado** [comment]
I'm using 1.8.5.3 and facing the same issue with PostgreSQL 10.14, but after the error I receive an INF saying:
 Hangfire SQL objects installed.
 
 And it's really working, so its a little bit confusing to see an error warning and everything working fine

**Comment by UrosBgd** [comment]
I can also confirm that 1.8.5.3 has the same problem. Reverting to 1.8.5.1 resolves it.

**Comment by Plasma** [comment]
Thanks @vytautask for the quick PR merge, version `1.8.5.4` resolves this issue for me now.
