### ISSUE TITLE
duplicate key value violates unique constraint "set_key_value_key"

### ISSUE THREAD

**Issue by Frazi1** [frankhommers/Hangfire.PostgreSql#198]
Creating this issue just to keep better track of things.

More details:
* https://github.com/frankhommers/Hangfire.PostgreSql/issues/191#issuecomment-872367869
* https://github.com/face-it/Hangfire.Tags/issues/39

**Comment by vytautask** [comment]
Should be fixed with the new release (1.8.5.3)
