### ISSUE TITLE
Configuration to specify schema/search_path

### ISSUE THREAD

**Issue by mlb5000** [frankhommers/Hangfire.PostgreSql#2]
In order to support scenarios where multiple systems may share Databases (but operate in separate schemas), or even for more control, it would be nice to be able to configure the schema where the Hangfire tables are installed, and maybe to prefix them so they don't collide with other tables if inserted into an existing schema.

**Comment by frankhommers** [comment]
Closed via e00246dddccaceec067bbde14a0bf597f4073fe8.
