### ISSUE TITLE
Schema creation timing decision

### ISSUE THREAD

**Issue by colotiline** [frankhommers/Hangfire.PostgreSql#206]
Hi.

I'm on 1.8.6 of Hangfire.PostgreSql which runs under ASP.NET Core and IaC. 

Why do you open connection and try to initiate schema when services are setup and not when app is configured? 

Doesn't that breaks `ConfigureServices` purpose? It's a DI setup and shouldn't have side effects like a schema or database creation.

**Details**
Hangfire's database doesn't exist until app's configuration step involved.

Adding Hangfire in `ConfigureServices`:
```
services.AddHangfire
(
    _ => _.UsePostgreSqlStorage
    (
        this.hangfireDbContextConnectionString
    )
);

services.AddHangfireServer();
```

Creating Hangfire's database in `Configure`:
```
using var hangfireDbContext =
    app
    .ApplicationServices
    .CreateScope()
    .ServiceProvider
    .GetService<HangfireDbContext>()!;

hangfireDbContext.Database.EnsureCreated();
```

But `UsePostgreSqlStorage` creates `PostgreSqlStorage` which connects to database which doesn't exist and it gets a PostgreSql exception.

**Comment by frankhommers** [comment]
What is your proposed solution?

If you don't like the behaviour you can create the schema up-front by hand.

**Comment by colotiline** [comment]
The workaround was to create the schema up-front.

I don't think that `UsePostgreSqlStorage` should try to connect to a database before any ORM request is executed, because:
* `EnsureCreated` is a standard way to create a database in EF Core.
* It's not possible to use IaC with current behaviour.

**Comment by frankhommers** [comment]
It's not a given that anyone uses EF Core next to this component.

So you want a static EnsureCreated to be callable?

**Comment by pprometey** [comment]
I faced such a situation. Current implementation is flawed and contrary to asp .net core standards

**Comment by frankhommers** [comment]
@pprometey and @colotiline : If you think it's flawed, we welcome your PR's to make it better.
Just mentioning that it is flawed does not help anyone.

**Comment by pprometey** [comment]
@frankhommers Identifying and localizing the problem is half the solution.
Okay, I understand your position. I'll see what I can do with the remaining half.

**Comment by frankhommers** [comment]
@colotiline or @pprometey is this something you are willing to fix?

**Comment by colotiline** [comment]
No.
