### ISSUE TITLE
Npgsql.PostgresException (0x80004005): 40001: could not serialize access due to concurrent update

### ISSUE THREAD

**Issue by KhorAMus** [frankhommers/Hangfire.PostgreSql#207]
I have more than one server in one app ( app.UseHangfireServer(options); was written  more than one time )
Error occures randomly when RecurringJob.AddOrUpdate is performing.  
I made a simple project in which this bug occures on every program start https://github.com/KhorAMus/HangfireTry
![image](https://user-images.githubusercontent.com/10596060/131641660-043210fd-2f25-4bf8-ad04-7a143989806f.png)

public void ConfigureServices(IServiceCollection services)
        {
            services.AddHangfire(x =>
            x.UsePostgreSqlStorage("User name = postgres; Password = 123; Host = localhost; Port = 5433; Database = HangfireTry;"));
            services.AddControllers();
        }

        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            var queues = Enumerable.Range(1, 10).Select(i => $"default{i}");
            foreach (var queue in queues)
            {
                var options = new BackgroundJobServerOptions
                {
                    WorkerCount = 1,
                    Queues = new[] { queue }
                };
                app.UseHangfireServer(options);
            }

            var recurringJobIds = Enumerable.Range(1, 100).Select(i => $"DeleteOldNotifications{i}");
            foreach (var recurringJobId in recurringJobIds)
            {
                RecurringJob.AddOrUpdate(recurringJobId, () => Console.WriteLine(recurringJobId),
                    "*/10 * * * *");//error may occures after that 
            }

            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            app.UseRouting();
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllerRoute(
                    name: "default",
                    pattern: "{controller=Home}/{action=Index}/{id?}");
            });
        }`

**Comment by frankhommers** [comment]
Not being able to obtain a lock is as designed. Does this crash stuff? Or does your IDE accidentally breaks on this only?

**Comment by KhorAMus** [comment]
@frankhommers No this doesn't crash stuff. It is just one of warnings that I received during debug. So is it ok to receive this warning?

**Comment by frankhommers** [comment]
Yes. Actually this is why the distributed locks exists so that not all service will pick up the same job.
