### ISSUE TITLE
Jobs stucked in queue for several hours.

### ISSUE THREAD

**Issue by styret1904** [frankhommers/Hangfire.PostgreSql#208]
Hangfire v1.7.25
Hangfire.PostgreSql: v1.8.6
.NET 5.0

Problem: 
Sometimes when processing jobs are running for a significant amount of time we have issues with enqueued jobs getting stucked in the queue and not being processed when the worker is available.  

We can see in our logs that Hangfire throws: _HangFire:locks:schedulepoller: Failed to lock with transaction_ 

And HangFire.PostgreSql throws:  _Could not serialize access due to concurrent update_ 

Here are the only config for our Hangfire.PostgreSql: 
` services.AddHangfire(x => {x.UsePostgreSqlStorage("ConnectionString") }
`

We have tried to configure `UseNativeDatabaseTransactions` to both true and false but nothing seems to help.

**Comment by ffMathy** [comment]
@styret1904 I have a feeling that this isn't the storage provider's fault. Have you tried submitting this issue at the main Hangfire repo?

**Comment by styret1904** [comment]
@ffMathy That's what i thought as well. I have submitted the same issue at the main HangFire repo as well. We can close this issuse.
