### ISSUE TITLE
Npgsql version

### ISSUE THREAD

**Issue by azygis** [frankhommers/Hangfire.PostgreSql#222]
Is there any way to support Npgsql 5.0.10 with latest Hangfire.PostgreSql packages?

Unfortunately, Npgsql follows EF Core versioning. Since Npgsql 6.0.x is only shipped with Npgsql.EntityFrameworkCore.PostgreSQL 6.0.x, we cannot use this provider from NuGet, so we're still stuck with a built dll which we have to use to fix #212.

**Comment by frankhommers** [comment]
Well, I don't know what is the best way. Some people are using Npgsql 6.0, which need to have their problems fixed due to the new handling DateTimes.

I am not sure how to get it compatible with both... Do you have any suggestions?

Check these:
#210 
#221

**Comment by azygis** [comment]
Probably the easiest solution would be to target netstandard2.0 (I think that's what the library targets today?) / net5.0 / net6.0 with different Npgsql versions between target frameworks using conditional item groups.

That is, if the database scripts are compatible with either npgsql version (why, I believe, they are). If not - there's a bigger project to implement: split the project to three separate libraries, with core features in one, and npgsql-version-specific features in two separate libraries.

I still think the first option of multitargeting is fine, maybe worth a shot.

**Comment by frankhommers** [comment]
I'd rather have it concentrated here. How about I make you a contributor of this repo?

**Comment by azygis** [comment]
Sure, I can help here.

**Comment by frankhommers** [comment]
@vytautask Can you give azygis access to AppVeyor? 

It would be nice if the appveyor scripts would procedure all the nupkg's as artificats at once, are you willing to try that @azygis ?

**Comment by vytautask** [comment]
Sure, I just need an email address from @azygis to do that.

**Comment by azygis** [comment]
Haven't used appveyor, but used plenty of other agents. Will try.

**Comment by azygis** [comment]
I have access to AppVeyor now, so probably my question is which route should I go? Split the libraries into three (Hangfire.PostgreSql.Core / Hangfire.PostgreSql.Npgsql5 / Hangfire.PostgreSql (which would be the current package with a reference to .Core instead of direct single package), or have a separate branch for Npgsql5? I personally prefer splitting since then there's no need to port anything to another branch.

**Comment by frankhommers** [comment]
Ehm, I think it would be best to end up with just two nupkg's and not three. But that's just based on my gut feeling.

**Comment by azygis** [comment]
Now the real pull request is in. I'm not entirely sure how appveyor does it's magic and pushes to NuGet, but I suppose it will just pick both nupkg files based on wildcard and push them both.

**Comment by frankhommers** [comment]
@azygis That isn't automated yet ;-)

For now we take the the artificats and upload them manually to NuGet

**Comment by frankhommers** [comment]
If you bump the versions in the PR I'll publish them to NuGet.

**Comment by azygis** [comment]
Bumped versions in csproj and updated README.md.
