### ISSUE TITLE
A transaction is already in progress; nested/concurrent transactions aren't supported.

### ISSUE THREAD

**Issue by DrexAt** [frankhommers/Hangfire.PostgreSql#225]
After upgrading to version 1.9.4 it's not possible to enqueue a job if there is already an ongoing transaction. 

This appears only on Linux as the handling differs on Windows. The bug occurs in `PostgreSqlStorage.cs` on line 257 where a new transaction is started.

I created a small Repro to showcase the bug. I tested it on a `mcr.microsoft.com/dotnet/sdk:6.0` docker image. Also, the test `CreateExpiredJob_EnlistsInTransaction` failed inside the container.

These are the expectation details: 
```
InvalidOperationException: A transaction is already in progress; nested/concurrent transactions aren't supported.
Npgsql.NpgsqlConnection.BeginTransaction(IsolationLevel level, bool async, CancellationToken cancellationToken)
Npgsql.NpgsqlConnection.BeginTransaction(IsolationLevel level)
System.Data.Common.DbConnection.BeginTransaction(IsolationLevel isolationLevel)
Hangfire.PostgreSql.PostgreSqlStorage+<>c__DisplayClass22_0<T>.<UseTransaction>b__0(DbConnection connection)
Hangfire.PostgreSql.PostgreSqlStorage.UseConnection<T>(DbConnection dedicatedConnection, Func<DbConnection, T> func)
Hangfire.PostgreSql.PostgreSqlStorage.UseTransaction<T>(DbConnection dedicatedConnection, Func<DbConnection, IDbTransaction, T> func, Nullable<IsolationLevel> isolationLevel)
Hangfire.PostgreSql.PostgreSqlConnection.CreateExpiredJob(Job job, IDictionary<string, string> parameters, DateTime createdAt, TimeSpan expireIn)
Hangfire.Client.CoreBackgroundJobFactory+<>c__DisplayClass14_0.<Create>b__2(int _)
Hangfire.Client.CoreBackgroundJobFactory.RetryOnException<T>(ref int attemptsLeft, Func<int, T> action)
Hangfire.Client.CoreBackgroundJobFactory.RetryOnException<T>(ref int attemptsLeft, Func<int, T> action)
Hangfire.Client.CoreBackgroundJobFactory.Create(CreateContext context)
Hangfire.Client.BackgroundJobFactory+<>c__DisplayClass12_0.<CreateWithFilters>b__0()
Hangfire.Client.BackgroundJobFactory.InvokeClientFilter(IClientFilter filter, CreatingContext preContext, Func<CreatedContext> continuation)
Hangfire.Client.BackgroundJobFactory+<>c__DisplayClass12_1.<CreateWithFilters>b__2()
Hangfire.Client.BackgroundJobFactory.CreateWithFilters(CreateContext context, IEnumerable<IClientFilter> filters)
Hangfire.Client.BackgroundJobFactory.Create(CreateContext context)
Hangfire.BackgroundJobClient.Create(Job job, IState state)
```

[HangfireTest.zip](https://github.com/frankhommers/Hangfire.PostgreSql/files/7711153/HangfireTest.zip)

**Comment by jhartmann123** [comment]
I just tested it with an SQL server connection and we've got the same issue there. As recently the transaction logic was copied from the SQL server implementation, that bug was copied with it. It is most probably a regression from making it compatible with mono, done in [this commit](https://github.com/HangfireIO/Hangfire/commit/b8ffde668604775e1e4b02f9cd396b3d4c241efe?diff=split).

I'll create a ticket in the HangfireIO repository with a repro.

**Comment by jhartmann123** [comment]
As this issue started to appear when the transaction logic was copied from `Hangfire.Sql` in [this commit](https://github.com/frankhommers/Hangfire.PostgreSql/commit/deaca23c7c99de005a5fd83d65a827973a506452), I've checked the behavior of `Hangfire.Sql`.

In that lib it also fails on windows with an exception `NotSupportedException: Enlisting in Ambient transactions is not supported.`.

However, `Hangfire.Sql` as I've seen from the first few looks, `Hangfire.Sql` doesn't have transaction scope enlistment support per se (like via `PostgreSqlStorageOptions.EnableTransactionScopeEnlistment`). That's probably the oversight.

Here's a simplified repro which also includes the SQL-Version plus .cmd to directly execute it in docker, if you don't have a Linux  with dotnet-sdk 6.0 available. As the culprint seems pretty clear to me, I'll also play around a bit and see if I can get that working.
[HangfireTests.zip](https://github.com/frankhommers/Hangfire.PostgreSql/files/7747836/HangfireTests.zip)
