### ISSUE TITLE
Hangfire.PostgreSql table schema name Lower/Upper case options.

### ISSUE THREAD

**Issue by denizzengin** [frankhommers/Hangfire.PostgreSql#226]
Hi everyone,

Are there an options to change defaul(lower) hangfire postgresql table name convention to upper-case? 
Because we migrate our all db tables sql server to postgre and we want to all table/db objects migrate with case sensitive named.
For instance,

current : Schema_Name.job
desired : Schema_Name."JOB"

**Comment by azygis** [comment]
No, not right now. Currently all table names are hardcoded in install scripts, but I personally see the use case for configuring them, so might as well implement some form of configuration.

**Comment by denizzengin** [comment]
Hi azygis,
thanks for your reply. I don't know is here right place but there are other issues when migrate sqlserver to postgres not only table/column name convension also table structure isn't matching exactly or may be wrong version installed.
Old version of hangfire sql server : 1.7.27
Current version hangfire postgre : 1.9.. I guess last release  
I updated all hangfire tables and their column names to lower case but now it gives "id" column doesn't exist but hangfire sqlserver didn't has "id" already.

**Comment by azygis** [comment]
I'm afraid there's not much we can help with here. Each provider is responsible for it's own database structure. You would need to migrate your data by hand by adjusting the scripts if you want to keep all the data.

**Comment by frankhommers** [comment]
Migration from another storage is indeed your own concern. Agree with @azygis. There is also no standard way of doing this I think.

About the casing we are open for PR's on this, but I don't think I am willing to put time in this.

So I am closing this awaiting a possible PR.
