### ISSUE TITLE
Consider merging this commit which adds indexes

### ISSUE THREAD

**Issue by bherila** [frankhommers/Hangfire.PostgreSql#23]
https://github.com/SEEK-Jobs/Hangfire.PostgreSql/commit/25c11b7fab847108abe3304c690b90405739d435

**Comment by vytautask** [comment]
Could you, please, create a PR with Install.v6.sql file created and those added (just double check if it does not exist already).

**Comment by frankhommers** [comment]
Yes, new things should always be added to a new Install.v{new}.sql file, so that when an existing user upgrades the Hangfire.PostgreSql component it will get all the enhancements/updates/fixes too.

**Comment by bherila** [comment]
Deprecated, will put into new PR.
