### ISSUE TITLE
42P01: relation "hangfire.schema" does not exist

### ISSUE THREAD

**Issue by anhaehne** [frankhommers/Hangfire.PostgreSql#236]
Hi,

UsePostgreSqlStorage throws the following error when my application starts:

```
Npgsql.PostgresException: '42P01: relation "hangfire.schema" does not exist

POSITION: 53'

   at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|213_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
```

This is the first time i start the application after installing hangfire and the postgre storage. If i change the schema to something else, for example 'public' i get the same error but with `42P01: relation "public.schema" does not exist`.

Frameworks:
.net 6.0.1
Hangfire.AspNetCore 1.7.28
Hangfire.PostgreSql 1.9.5
Npgsql.EntityFrameworkCore.PostgreSQL 6.0.2

I connect to a docker container running in docker for windows. The image is `postgres:latest`. My connection string is `uid=postgres;password=postgres;Server=[::1];Port=5432;Database=HangfireDatabase;`

**Comment by azygis** [comment]
How does your `UsePostgreSqlStorage` call look like?

**Comment by anhaehne** [comment]
I'm using the new top level programm style:

``` csharp
var builder = WebApplication.CreateBuilder(args);

[...]

builder.Services.AddHangfire(config => config.UsePostgreSqlStorage(builder.Configuration.GetConnectionString("HangfireConnection")));

var app = builder.Build();

app.UseHangfireServer();
app.UseHangfireDashboard();

[...]
```

**Comment by azygis** [comment]
Would you be able to show the logs from the start all the way to the exception? Debug level for Hangfire "namespace" would be great. It's kinda suspicious that the object installer doesn't actually install the scripts.

**Comment by anhaehne** [comment]
Everything is set to debug:

```
"Logging": {
    "LogLevel": {
      "Default": "Debug",
      //"Microsoft.AspNetCore": "Warning",
      //"Microsoft.EntityFrameworkCore": "Warning"
    }
  }
```

The error is not logged to the log
```
info: Hangfire.PostgreSql.PostgreSqlStorage[0]
      Start installing Hangfire SQL objects...
info: Hangfire.PostgreSql.PostgreSqlStorage[0]
      Hangfire SQL objects installed.
info: Hangfire.BackgroundJobServer[0]
      Starting Hangfire Server using job storage: 'PostgreSQL Server: Host: [::1], DB: SerienfansHangfireDatabase, Schema: hangfire'
info: Hangfire.BackgroundJobServer[0]
      Using the following options for SQL Server job storage:
info: Hangfire.BackgroundJobServer[0]
          Queue poll interval: 00:00:15.
info: Hangfire.BackgroundJobServer[0]
          Invisibility timeout: 00:30:00.
info: Hangfire.BackgroundJobServer[0]
      Using the following options for Hangfire Server:
          Worker count: 20
          Listening queues: 'default'
          Shutdown timeout: 00:00:15
          Schedule polling interval: 00:00:15
warn: Microsoft.EntityFrameworkCore.Infrastructure[10410]
      'AddEntityFramework*' was called on the service provider, but 'UseInternalServiceProvider' wasn't called in the DbContext options configuration. Consider removing the 'AddEntityFramework*' call, as in most cases it's not needed and may cause conflicts with other products and services registered in the same service provider.
info: Hangfire.Server.BackgroundServerProcess[0]
      Server andre-pc:3572:4ef36474 successfully announced in 98,7662 ms
info: Hangfire.Server.BackgroundServerProcess[0]
      Server andre-pc:3572:4ef36474 is starting the registered dispatchers: ServerWatchdog, ServerJobCancellationWatcher, ExpirationManager, Worker, DelayedJobScheduler, RecurringJobScheduler...
info: Hangfire.Server.BackgroundServerProcess[0]
      Server andre-pc:3572:4ef36474 all the dispatchers started
```

I've just tried starting the application withou the debugger and now the hangfire schema was created. But now when i try to start with the debugger again, i get the following exception:

```
System.Resources.MissingManifestResourceException: 'Requested resource `Hangfire.PostgreSql.Scripts.Install.v16.sql` was not found in the assembly `Hangfire.PostgreSql, Version=1.9.5.0, Culture=neutral, PublicKeyToken=null`.'
   at Hangfire.PostgreSql.PostgreSqlObjectsInstaller.GetStringResource(Assembly assembly, String resourceName)
```

**Comment by azygis** [comment]
Okay, so the debugger breaks processing of your current thread, but it does not break processing of background threads (which Hangfire uses). Since by the time background worker tried to do it's work schema has not been created, an exception was thrown. Now you allowed the schema to be created and everything works correctly.

Regarding missing resource exception - you can ignore that one, it's intentional and is caught internally (means there are no remaining updates).

**Comment by frankhommers** [comment]
v16 should exist I think?

**Comment by azygis** [comment]
Not in [1.9.5](https://github.com/frankhommers/Hangfire.PostgreSql/tree/1.9.5/src/Hangfire.PostgreSql/Scripts). Did you forget to publish the package after merging the last pull request? The 1.9.5 tag was created 20 days ago, while master was updated 15 days ago, and that last update did have a new install script. In any case - 1.9.5 does not have it yet == it works as expected in this particular issue.

**Comment by frankhommers** [comment]
Ah my bad I guess ;-)

**Comment by frankhommers** [comment]
I think I need to create a 1.9.6 to resolve this I guess, that feels a bit weird. I'll do it for the next commit.

**Comment by azygis** [comment]
Just to be clear - there's nothing to resolve in this particular issue. The problem was with how @anhaehne ran the application. Hangfire will still try to run the jobs in the background thread while the debugging session is active on another thread. Since the objects were not installed by the time Hangfire tried to do it's job, an exception was thrown. Once he just ran the app properly, allowing schema to be migrated, everything was fine. The `MissingManifestResourceException` is also perfectly fine and can be ignored with the version he used.

But I agree, the new package needs to be published with the latest v16 script. It's merged long ago, yet still not in NuGet.
