### ISSUE TITLE
Are there plans to support transactions in the future?

### ISSUE THREAD

**Issue by lncendia** [frankhommers/Hangfire.PostgreSql#241]
The MS SQL extension for hangfire has long abandoned the invisibility timeout in favor of using transitions, which helped to avoid restarting tasks and instantly starting them at an emergency end. Are there any plans to add such functionality in the future?

**Comment by lncendia** [comment]
And what about Sliding In visibility Timeout?

**Comment by Frazi1** [comment]
> The MS SQL extension for hangfire has long abandoned the invisibility timeout in favor of using transitions, which helped to avoid restarting tasks and instantly starting them at an emergency end. Are there any plans to add such functionality in the future?

As far as I'm aware, Ms SQL uses sliding invisibility timeout to handle this. I haven't seen the transaction approach you mentioned. @Incendia can you please point me at it?

**Comment by lncendia** [comment]
https://www.hangfire.io/blog/2015/07/31/hangfire-1.5.0-beta.html

"Instant Re-Queue for SQL Server
Say goodbye to confusing invisibility timeout with unexpected background job retries after 30 minutes (by default) when using SQL Server. New Hangfire.SqlServer implementation uses plain old transactions to fetch background jobs and hide them from other workers.
Even after ungraceful shutdown, the job will be available for other workers instantly, without any delays."

In further development notes, SlidingInvisibilityTimeout appears, I'm also not sure which of these is actually being used at the moment.

**Comment by Frazi1** [comment]
I suggest closing this issue in favor of #209 because it is a duplicate.

**Comment by azygis** [comment]
Indeed!
