### ISSUE TITLE
An unhandled exception occurred while processing the request.

### ISSUE THREAD

**Issue by mheidari988** [frankhommers/Hangfire.PostgreSql#259]
We are trying to wire up Hangfire.PostgreSql with our AspNetZero project, but after first run, and when we click on Servers tab in the Dashboard we face with the following Exception:

**unhandled exception occurred while processing the request.**
![hangfire-dapper-error](https://user-images.githubusercontent.com/29603137/186095901-d352fbe8-062a-4eb0-af73-0ebaf3cab564.jpg)

Configurations:

            services.AddHangfire(config =>
            {
                config.UsePostgreSqlStorage(_appConfiguration.GetConnectionString("Hangfire"), new PostgreSqlStorageOptions
                {
                    SchemaName = "public",
                    PrepareSchemaIfNecessary = true,
                    EnableTransactionScopeEnlistment = true,
                });
            });

I tried different options, but same error occurs.

Using:
Dotnet core 6
AspNetZero (AspBoilerplate)
Hangfire.PostgreSql v1.9.8

**Comment by tomi936** [comment]
Same issue for me too, and at jobs tab.

![image](https://user-images.githubusercontent.com/3695931/190642371-a579f8b1-e85d-4485-8a14-c16fa51b339c.png)

**Comment by frankhommers** [comment]
Are you guys using NodaTime by any chance? It seems like Deserialization of DateTime(Offset)s fail.

**Comment by mheidari988** [comment]
> Are you guys using NodaTime by any chance? It seems like Deserialization of DateTime(Offset)s fail.

No, we don't use NodaTime

**Comment by azygis** [comment]
Both of you screenshots show different date styles. I don't think the `DATESTYLE` set on the PostgreSQL instance has any impact, but I can't say for certain.

Tried creating a dummy project [here](https://aspnetboilerplate.com/Templates), following the tutorials [here](https://aspnetboilerplate.com/Pages/Documents/EF-Core-PostgreSql-Integration) (except the switch which is not correct in the first place) and [here](https://aspnetboilerplate.com/Pages/Documents/Hangfire-Integration), and the server list in the dashboard works just fine. Please attach a repro if you face any issues. Closing until then.
