### ISSUE TITLE
Recurring jobs not working.

### ISSUE THREAD

**Issue by srikanthg508** [frankhommers/Hangfire.PostgreSql#264]
![image](https://user-images.githubusercontent.com/94897489/193083816-2c0a1996-d1bc-4230-9cde-a818195a386a.png)

How to resolve above issue...????

**Comment by azygis** [comment]
Looks like the application was killed while the lock was placed to `hangfire.lock` table. Clear the table manually and it should be ok.

**Comment by srikanthg508** [comment]
Present there will be no data in the lock table. Even though the issue will be coming.
