### ISSUE TITLE
DefaultConnectionBuilder

### ISSUE THREAD

**Issue by awavevladimirmironov** [frankhommers/Hangfire.PostgreSql#269]
I installed a new version of 1.9.9 and have PostgreSQL and lib can`t find DefaultConnectionBuilder.
![devenv_PCkTVhauTY](https://user-images.githubusercontent.com/83659735/197386963-1b69a9ca-c381-4464-ba86-10ed01aaee4b.png)
What am I missing?

**Comment by azygis** [comment]
I believe you are trying to use the docs for enabling SSL support in README. I'm afraid that section is somewhat misleading - there is no builder out of the box, only for our own tests.

Technically you could implement the `IConnectionFactory` in your solution and set up the connection similar to how the README shows, simply returning the connection from your factory with the certificate file set.

We also have a way of setting up the connection further, there's a [separate overload](https://github.com/frankhommers/Hangfire.PostgreSql/blob/master/src/Hangfire.PostgreSql/PostgreSqlBootstrapperConfigurationExtensions.cs#L68) for that, and the setup would be something similar to this:

```
config.UsePostgreSqlStorage(
    Configuration.GetConnectionString("HangfireConnection"), // connection string
    connection => // connection setup - gets called after instantiating the connection and before any calls to DB are made
    {
        connection.ProvideClientCertificatesCallback += clientCerts =>
        {
            clientCerts.Add(X509Certificate.CreateFromCertFile("[CERT_FILENAME]"));
        };
    },
    new PostgreSqlStorageOptions() // no overload without options, so just pass the default or configured options
);
```

**Comment by awavevladimirmironov** [comment]
thanks. it help
