### ISSUE TITLE
Server Id column is to small for autogenerated ids

### ISSUE THREAD

**Issue by everfrown** [frankhommers/Hangfire.PostgreSql#28]
Hi,

There was schema update in 1.5.4 version
ALTER TABLE [HangFire].[Server] ALTER COLUMN [Id] NVARCHAR (100) NOT NULL;
commit (https://github.com/HangfireIO/Hangfire/commit/d903a297f6c6d312c6409576b5c0062026bccd89)

The server id is now autogenerated and can be more then 50 character length.

Proof: https://discuss.hangfire.io/t/server-bootstrapper-error-hangfire-server-serverbootstrapper/1232

**Comment by bherila** [comment]
@everfrown can you submit a PR? I have not had any issue with the current configuration.

**Comment by vytautask** [comment]
It was done in v5 install script a while ago.
