### ISSUE TITLE
Postgres Syntax Error

### ISSUE THREAD

**Issue by brian-mouton-at-fis** [frankhommers/Hangfire.PostgreSql#281]
This section of code generates a SQL segment that causes a syntax error in the Hangfire UI when running on PostgreSQL 12.8.
My workaround is to download to version 1.9.9.

I suspect if you cahnge all the `SUM"value") value` into `SUM("value") as value`, it could fix the problem.

https://github.com/frankhommers/Hangfire.PostgreSql/blob/4713f3001b9d0f5413397d97c74df5f34a7f376c/src/Hangfire.PostgreSql/PostgreSqlMonitoringApi.cs#L282

`          
SELECT "statename" "State", COUNT("id") "Count" 
          FROM "hangfire"."job"
          WHERE "statename" IS NOT NULL
          GROUP BY "statename";

          SELECT COUNT(*) 
          FROM "hangfire"."server";

          SELECT SUM("value") FROM
            (SELECT SUM("value") value
            FROM "hangfire"."counter" 
            WHERE "key" = 'stats:succeeded'
            UNION ALL
            SELECT SUM("value") value
            FROM "hangfire"."aggregatedcounter" 
            WHERE "key" = 'stats:succeeded') c;

          SELECT SUM("value") FROM
            (SELECT SUM("value") value
            FROM "hangfire"."counter" 
            WHERE "key" = 'stats:deleted'
            UNION ALL
            SELECT SUM("value") value
            FROM "hangfire"."aggregatedcounter" 
            WHERE "key" = 'stats:deleted') c;

          SELECT COUNT(*) 
          FROM "hangfire"."set" 
          WHERE "key" = 'recurring-jobs';`

**Comment by azygis** [comment]
This has already been fixed with #280, will be published to nuget soon.
