### ISSUE TITLE
PostgreSql Exception When trying to load the hangfire dashboard

### ISSUE THREAD

**Issue by akhakpouri** [frankhommers/Hangfire.PostgreSql#283]
.NET 6;
Npgsql 6.0.38;
Hangfire.PostgreSql 1.9.10;
Hangfire.Core 1.7.33;
PostgreSQL 13.7;

When I try to access the hangfire dashboard, I get the following exception.

`
PostgresException: 42601: syntax error at or near "value" POSITION: 59

    Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|215_0(NpgsqlConnector connector, bool async, DataRowLoadingMode dataRowLoadingMode, bool readingNotifications, bool isReadingPrependedMessage)
    Npgsql.NpgsqlDataReader.NextResult(bool async, bool isConsuming, CancellationToken cancellationToken)
    Npgsql.NpgsqlDataReader.NextResult()
    Dapper.SqlMapper+GridReader.NextResult() in SqlMapper.GridReader.cs
    Dapper.SqlMapper+GridReader.ReadRow<T>(Type type, Row row) in SqlMapper.GridReader.cs
    Dapper.SqlMapper+GridReader.ReadSingle<T>() in SqlMapper.GridReader.cs
    Hangfire.PostgreSql.PostgreSqlMonitoringApi.<GetStatistics>b__24_0(IDbConnection connection)
    Hangfire.PostgreSql.PostgreSqlStorage.UseConnection<T>(DbConnection dedicatedConnection, Func<DbConnection, T> func)
    Hangfire.PostgreSql.PostgreSqlMonitoringApi.UseConnection<T>(Func<IDbConnection, T> func)
    Hangfire.PostgreSql.PostgreSqlMonitoringApi.GetStatistics()
    Hangfire.Dashboard.RazorPage.<Assign>b__44_0()
    System.Lazy<T>.ViaFactory(LazyThreadSafetyMode mode)
    System.Lazy<T>.ExecutionAndPublication(LazyHelper executionAndPublication, bool useDefaultConstructor)
    System.Lazy<T>.CreateValue()
    Hangfire.Dashboard.RazorPage.get_Statistics()
    Hangfire.Dashboard.Pages.HomePage.Execute()
    Hangfire.Dashboard.RazorPage.TransformText(string body)
    Hangfire.Dashboard.RazorPage.ToString()
    Hangfire.Dashboard.RazorPageDispatcher.Dispatch(DashboardContext context)
    Hangfire.Dashboard.AspNetCoreDashboardMiddleware.Invoke(HttpContext httpContext)
    Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.InvokeCore(HttpContext context, PathString matchedPath, PathString remainingPath)
    Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

`

**Comment by azygis** [comment]
Already reported in [this comment](https://github.com/frankhommers/Hangfire.PostgreSql/issues/282#issuecomment-1415286683) and fixed with #280. @frankhommers has to push the library to NuGet.

**Comment by akhakpouri** [comment]
@azygis I don't understand why you closed this issue. You mentioned in [this comment](https://github.com/frankhommers/Hangfire.PostgreSql/issues/282#issuecomment-1415378853) that the problem described in the issue and the comment are not the same.
Did your team provide an update for the problem mentioned in this issue?

The last stable release is `v. 1.9.10` where this problem is introduced. You mentioned that a new version of the nuget package has been published, but I'm not able to find it.

**Comment by azygis** [comment]
I closed the issue because it is fixed with #280 as mentioned previously.

If you check the stack trace in the referenced comment and my reply to it again, you'll see that the issue from the comment is not related **to that specific OP's issue**, but it's exactly the same as reported by you.

I did not mention that the package _has been_ published - I said it _has to be_ published.

**Comment by akhakpouri** [comment]
Ahh! That makes sense. I was under the impression that the fix had already been published. 

Thank you for your help!

**Comment by azygis** [comment]
Sorry for the wait. The package has been pushed to NuGet now.
