### ISSUE TITLE
Support for NpgSQL 3.x

### ISSUE THREAD

**Issue by tom-gerken** [frankhommers/Hangfire.PostgreSql#29]
Npgsql > 3.x removed support for writing a parameter with an IEnumerable value, use .ToList()/.ToArray() instead

**Comment by frankhommers** [comment]
Already addressed:

https://github.com/frankhommers/Hangfire.PostgreSql/pull/21
https://github.com/frankhommers/Hangfire.PostgreSql/pull/17
https://github.com/frankhommers/Hangfire.PostgreSql/issues/16
