### ISSUE TITLE
Could not place a lock on the resource: Lock timeout

### ISSUE THREAD

**Issue by topwik** [frankhommers/Hangfire.PostgreSql#31]
Started seeing a lot of these errors popping up. 

Could not place a lock on the resource 'HangFire:locks:schedulepoller' and 'HangFire:recurring-jobs:lock': Lock timeout
Can anyone offer suggestions on how to resolve this?

What is going on? Need some suggestions.

Error occurred during execution of 'DelayedJobScheduler' process. Execution will be retried (attempt 15 of 2147483647) in 00:03:41 seconds. Hangfire.PostgreSql.PostgreSqlDistributedLockException: Could not place a lock on the resource 'HangFire:locks:schedulepoller': Lock timeout. at Hangfire.PostgreSql.PostgreSqlDistributedLock.PostgreSqlDistributedLock_Init_Transaction(String resource, TimeSpan timeout, IDbConnection connection, PostgreSqlStorageOptions options) at Hangfire.PostgreSql.PostgreSqlConnection.AcquireDistributedLock(String resource, TimeSpan timeout) at Hangfire.Server.DelayedJobScheduler.EnqueueNextScheduledJob(BackgroundProcessContext context) at Hangfire.Server.DelayedJobScheduler.Execute(BackgroundProcessContext context) at Hangfire.Server.AutomaticRetryProcess.Execute(BackgroundProcessContext context)

Error occurred during execution of 'RecurringJobScheduler' process. Execution will be retried (attempt 13 of 2147483647) in 00:02:44 seconds. Hangfire.PostgreSql.PostgreSqlDistributedLockException: Could not place a lock on the resource 'HangFire:recurring-jobs:lock': Lock timeout. at Hangfire.PostgreSql.PostgreSqlDistributedLock.PostgreSqlDistributedLock_Init_Transaction(String resource, TimeSpan timeout, IDbConnection connection, PostgreSqlStorageOptions options) at Hangfire.PostgreSql.PostgreSqlDistributedLock..ctor(String resource, TimeSpan timeout, IDbConnection connection, PostgreSqlStorageOptions options) at Hangfire.PostgreSql.PostgreSqlConnection.AcquireDistributedLock(String resource, TimeSpan timeout) at Hangfire.Server.RecurringJobScheduler.Execute(BackgroundProcessContext context) at Hangfire.Server.AutomaticRetryProcess.Execute(BackgroundProcessContext context)

**Comment by vytautask** [comment]
Probably has something to do with Npgsql. I've read they fixed a lot of deadlocks in the latest version of the library (http://www.npgsql.org/).

**Comment by towts** [comment]
but does the latest hangfire postgres nuget play nice with latest version of npgsql?

**Comment by vytautask** [comment]
Do not know if this project can (IMHO it is not maintained anymore), but there are forks which will do. Just search in the nuget "hangfire postgresql storage" and choose.

**Comment by towts** [comment]
yup. found hangfire postgres revised by clicking on your name. https://github.com/vytautask/Hangfire.PostgreSql 

regards!

**Comment by frankhommers** [comment]
@vytautask I would be happy to make let us maintain this github repo together and/or accept your pull requests! ;-)

**Comment by vytautask** [comment]
@frankhommers I'm all for that. However the problem is not the repo but the packages in nuget (there are no new versions). Is it possible to publish new versions to https://www.nuget.org/packages/Hangfire.PostgreSql/ ? Do you still have access to that package?

**Comment by bherila** [comment]
@frankhommers and @vytautask I think it would be good to have multiple owners of both this repo and the Nuget repo. I am happy to review/rebase/merge pull requests if it would help. I have not been able to contribute many lines of code at this point but will be happy to facilitate if that would be helpful.

Regards,
Ben

**Comment by vytautask** [comment]
@bherila my thoughts exactly. The only reason I forked and created "Revised" version was because the nuget versions were so old. So, if we establish multiple ownership (github and nuget, both), I could abandon my fork and just push to this one.

**Comment by frankhommers** [comment]
I made an issue ( https://github.com/frankhommers/Hangfire.PostgreSql/issues/36 ) to manage the working together stuff. Lets keep this issue open for what it was intended for.

**Comment by gdlcf88** [comment]
Hi @vytautask , I am using Hangfire.PostgreSql 1.6.4 and the framework [Abp vnext](https://github.com/abpframework/abp).

```
    public class MyJob : ITransientDependency
    {
        public MyJob(IUnitOfWorkManager unitOfWorkManager)
        {
            _unitOfWorkManager = unitOfWorkManager;
        }

        public async Task ExecuteAsync()
        {
            using var uow = _unitOfWorkManager.Begin(new AbpUnitOfWorkOptions{ IsTransactional = true });
        }
    }
```

It throws the same error. But if I disable the transaction, it works.

**Comment by gdlcf88** [comment]
The problem disappeared, perhaps because of the database itself.

**Comment by vizeke** [comment]
Had the same problem.

It looks like setting the DistributedLockTimeout property of PostgreSqlStorageOptions solved the issue.

Started with 1 min and no problems so far.

```
services.AddHangfire(config => config
 .UsePostgreSqlStorage(hangfireSettings.ConnectionString, new PostgreSqlStorageOptions
                 {
                     InvisibilityTimeout = TimeSpan.FromMinutes(5),
                     QueuePollInterval = TimeSpan.FromMilliseconds(200),
                     DistributedLockTimeout = TimeSpan.FromMinutes(1),
                 })
```
