### ISSUE TITLE
Could we get an updated package pushed to Nuget?

### ISSUE THREAD

**Issue by ericgreenmix** [frankhommers/Hangfire.PostgreSql#32]

**Comment by bherila** [comment]
We should try to merge in forks to this repo, make sure everything works, and then release new packages. @frankhommers let me know if you would like me to help with this.

**Comment by frankhommers** [comment]
@bherila sure! Help me ;-)

**Comment by bherila** [comment]
@frankhommers can you add me as an owner to this: https://www.nuget.org/packages/Hangfire.PostgreSql/

alternatively here is how to update it: 

1. download the .nupkg here (or build it) https://github.com/frankhommers/Hangfire.PostgreSql/releases/tag/1.4.0
2. upload to nuget.org

Sorry for the delay as I was traveling. 

Thanks,
Ben

**Comment by bherila** [comment]
also @vytautask what should we do with [Hangfire.PostgreSql.Revised](https://www.nuget.org/packages/Hangfire.PostgreSql.Revised/)?

**Comment by vytautask** [comment]
@bherila as soon as @frankhommers uploads (or gives us access to do so) the new version to nuget I will place redirects / more info in my Revised version.

**Comment by jmangue** [comment]
I would also love to see 1.4.1 pushed up to Nuget.org 😁

**Comment by vytautask** [comment]
1.4.2 pushed to NuGet. Enjoy!

**Comment by jmangue** [comment]
Thanks vytautask! 🎉
