### ISSUE TITLE
CoreCLR

### ISSUE THREAD

**Issue by jchannon** [frankhommers/Hangfire.PostgreSql#34]
Any plans to support CoreCLR because the main Hangfire project does? Thanks 😄

**Comment by bherila** [comment]
@jchannon does npgsql support CoreCLR?

**Comment by vytautask** [comment]
@bherila yes. It does.

**Comment by fortinmike** [comment]
Any progress on this? We really need PostgreSQL support in our ASP.NET Core server.

I found this fork which compiles successfully for .NET Core (it's also on Nuget):
https://github.com/zhongzf/Hangfire.PostgreSql.NetCore/commit/9b199b22d3f59023750c93e787fa1edc97b901cb

However, I can't seem to make it work; the Dashboard explodes with an exception. **I couldn't find a way to contact the fork's author**. Maybe this rings a bell?

    PostgresException: 42P01: relation "hangfire.counter" does not exist

I can't tell if it fails because the port is incomplete / incorrect or if it's because the way I'm setting it up:

```csharp
public void AddAppServicesTo(IServiceCollection services)
{
    var storage = new PostgreSqlStorage(Configuration.GetConnectionString("DefaultConnection"));
    services.AddHangfire(c => c.UseStorage(storage));
}

private void ConfigureApp(IHostingEnvironment env, IApplicationBuilder app)
{
    app.UseHangfireServer(new BackgroundJobServerOptions
        {
            ServerName = "Default",
            WorkerCount = 2,
            Queues = new[] { JobQueue.Default.Name }
        });
}
```

It's the same setup code as I was using with SQL Server, except I call `UseStorage()` with a `PostgreSqlStorage` instance instead of using `UseSqlServerStorage()`.

Any pointers?

**Comment by vytautask** [comment]
@fortinmike could you check out this PR: #42 ?
Does that work for you?

**Comment by fortinmike** [comment]
I'm getting the error mentioned above when using [Hangfire.PostgreSql.NetCore](https://www.nuget.org/packages/Hangfire.PostgreSql.NetCore), which is the same as PR #42. Everything builds fine but I get this at runtime when accessing the dashboard:

    PostgresException: 42P01: relation "hangfire.counter" does not exist

Could this be related to the [comment](https://github.com/frankhommers/Hangfire.PostgreSql/pull/42#issuecomment-245248813) by @alasvant on that PR?

Taking a look at the database with pgAdmin, there are no schema nor tables related to Hangfire there. The connection string provided to Hangfire is the same that my app uses for its main storage (same DB). Might this have an impact?

Here are some logs, if that can help:

```
2016-08-26 12:11:05.432 -04:00 [Information] (Thread #1) Start installing Hangfire SQL objects...
2016-08-26 12:11:05.433 -04:00 [Information] (Thread #1) Hangfire SQL objects installed.
2016-08-26 12:11:05.454 -04:00 [Information] (Thread #1) Starting Hangfire Server
2016-08-26 12:11:05.455 -04:00 [Information] (Thread #1) Using job storage: 'PostgreSQL Server: Host: localhost, DB: Focus, Schema: hangfire'
2016-08-26 12:11:05.455 -04:00 [Information] (Thread #1) Using the following options for SQL Server job storage:
2016-08-26 12:11:05.456 -04:00 [Information] (Thread #1)     Queue poll interval: 00:00:15.
2016-08-26 12:11:05.456 -04:00 [Information] (Thread #1)     Invisibility timeout: 00:30:00.
2016-08-26 12:11:05.456 -04:00 [Information] (Thread #1) Using the following options for Hangfire Server:
2016-08-26 12:11:05.456 -04:00 [Information] (Thread #1)     Worker count: 2
2016-08-26 12:11:05.456 -04:00 [Information] (Thread #1)     Listening queues: 'default'
2016-08-26 12:11:05.457 -04:00 [Information] (Thread #1)     Shutdown timeout: 00:00:15
2016-08-26 12:11:05.457 -04:00 [Information] (Thread #1)     Schedule polling interval: 00:00:15
```

**Comment by alasvant** [comment]
@fortinmike there is a new release of Hangfire.PostgreSql.NetCore NuGet package (v1.4.3 by zhongzf) that fixes the database not created issue.

**Comment by vytautask** [comment]
@fortinmike @alasvant @bherila 
First of all, thank you all for your interest and participation in this feature development!
I've merged Core into master, however current build scripts does not work with the new structure. As I am extremely busy nowadays, could someone take care of that?

**Comment by fortinmike** [comment]
Thanks for updating the lib, @vytautask ! I tried migrating from `Hangfire.PostgreSql.NetCore` to `Hangfire.PostgreSql` but was met with this error. I guess it's a small omission in the package definition:

    package Hangfire.PostgreSql 1.4.4 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Hangfire.PostgreSql
    1.4.4 supports: net452 (.NETFramework,Version=v4.5.2)                                                                                  
    One or more packages are incompatible with .NETCoreApp,Version=v1.0.
