### ISSUE TITLE
Maintain Hangfire.PostgreSql together

### ISSUE THREAD

**Issue by frankhommers** [frankhommers/Hangfire.PostgreSql#36]
See title ;-)

For now I added @bherila and @vytautask as collaborators.

**Comment by vytautask** [comment]
@frankhommers What about Nuget packages? Do you still have access to Nuget? Will you be able to upload our renewed packages?

**Comment by mchinchilla** [comment]
Nuget package Updated would be great!!

**Comment by vytautask** [comment]
I just did https://github.com/frankhommers/Hangfire.PostgreSql/releases/tag/1.4.0
@frankhommers, maybe you could upload that to Nuget? That's if your QA approves my changes :)

**Comment by mchinchilla** [comment]
@vytautask thanks, I just tested it works perfectly!!!

**Comment by vytautask** [comment]
I took a liberty and created AppVeyor badge in Readme. It automatically runs tests after each push and should inform of any problems that would occur automatically.

**Comment by mchinchilla** [comment]
Excellent Job, Thank you!!

**Comment by frankhommers** [comment]
@vytautask I have to examine/QA everything. I will have time for this next week (around august 18th). Of course I still have NuGet access. It's only the ApiKey that's necessary, right? Also I have sent you a message with my contact details to your email address.

**Comment by bherila** [comment]
Yes, only the ApiKey is necessary but rather than share your ApiKey, Nuget.org provides a way to allow access to others to publish packages. We could also publish packages as PreRelease or to a private feed for testing.

**Comment by frankhommers** [comment]
Give me your nuget account names, and I can and you two as owners.

**Comment by bherila** [comment]
I'm bherila on nuget @frankhommers

**Comment by vytautask** [comment]
@frankhommers could you, please, add webhook to https://ci.appveyor.com/api/github/webhook?id=a01vpyliv5mh9xac ?
That would perform build every time changes are pushed.

**Comment by frankhommers** [comment]
@vytautask I added the webhook.

**Comment by Dresel** [comment]
Thanks for all your efforts, I really appreciate that.

**Comment by ahydrax** [comment]
Hi @frankhommers ! Can I join as collaborator?

**Comment by bherila** [comment]
Hi @ahydrax is there something you needed help merging?

**Comment by ahydrax** [comment]
Hi @bherila ! I just want to be more "involved" into developing process :)

**Comment by bherila** [comment]
We are doing it 😄  closing this issue!
