### ISSUE TITLE
Schema version not updated

### ISSUE THREAD

**Issue by avichapmannoq** [frankhommers/Hangfire.PostgreSql#38]
When upgrading to version 4 of the database schema, `Install.v4.sql` relies on checking if the `schema` table contains '4'. This doesn't seem to happen.

In testing the query in `PostgreSqlObjectsInstaller`:

```
var bumpVersionSql = string.Format(
   "INSERT INTO \"{0}\".\"schema\"(\"version\") " +
   "SELECT @version \"version\" WHERE NOT EXISTS (SELECT @previousVersion FROM \"{0}\".\"schema\")", schemaName);
```

I discovered that this only inserts a schema number if there is no existing number already.

The result seems to be that script v4 runs every time and fails after the first time.

**Comment by vytautask** [comment]
Thanks for the issue!
It is hard for me to understand the problem so please be patient and explain a little bit more :)
The theory is that the install script (Install.v4.sql) raises an error if the v4 version is applied and it results in the following lines (version bump) to not be executed. The problem is, that v4 is not executed always?

**Comment by avichapmannoq** [comment]
Hi. I found this when investigating that error showing up in my log files. It is not a 'version-already-applied' exception. Instead, it gets past that point in the script and fails on `ALTER TABLE "counter" ADD COLUMN "updatecount" integer NOT NULL DEFAULT 0;`, since that column already exists from the last execution of the script.

My understanding is that there needs to be a `4` in the `schema` table after Install.v4.sql is executed to cause everything to work correctly. But instead, there is only a three, even though clearly (based on the database structure) all three scripts have run.

(By the way, Install.v5.sql seems to remove the `4` and replace it with a `5`. So even if the `4` is manually put in, that only solves the problem for one iteration.)

**Comment by vytautask** [comment]
Please download the newest version (https://github.com/frankhommers/Hangfire.PostgreSql/releases/tag/1.4.1) and give it a try. If an attempt fails and it is possible, remove "hangfire" scheme from DB first.

**Comment by avichapmannoq** [comment]
Thanks. That worked.
