### ISSUE TITLE
Consider using sql enum for statename field

### ISSUE THREAD

**Issue by bherila** [frankhommers/Hangfire.PostgreSql#41]
Open to discussion before anyone switches it :)

![image](https://cloud.githubusercontent.com/assets/1422004/17748854/226e3b22-6470-11e6-9621-5f5eaa7aa926.png)

**Comment by vytautask** [comment]
Pros: better performance (maybe).
Cons: adding new value / changing old will require DB upgrade scripts.
However, this particular field is unlikely to change (IMHO).

**Comment by frankhommers** [comment]
Maybe a statetype table with static contents would be better because we could use it in #40 as well? And that way the new values/old values are a bit easier to update.

**Comment by pieceofsummer** [comment]
Hangfire is extensible, so *any* state (not only those defined in Hangfire.Core) can appear there because of custom IElectState filters.

Changing this field into enum is basically denying the extensibilty of the state machine, and a risk of incompatibility with other Hangfire extensions.
