### ISSUE TITLE
Consider using caching for sql query strings

### ISSUE THREAD

**Issue by ahydrax** [frankhommers/Hangfire.PostgreSql#45]
Very often I see in the code the following constructions:
`"SELECT SMTH FROM " + _options.SchemaName + ".tableName"`
which produces a lot of memory allocations. The obvious solution is to replace concatenation by interpolation. But performance will be remain almost same because query strings is being built for every method call. I propose to cache query strings somehow in order to reduce number of allocations.
For example, create a PostgresSqlQueryProvider which will be accepts PostgreSqlStorageOptions and it will produce sql queries from templates.
The api will be: `provider.BuildQuery("SELECT SMTH FROM {schemaName}.tableName")`

Let's discuss :)

**Comment by vytautask** [comment]
I do not believe I understand the problem.
Is this really an issue (speed)? String concatenation speed makes no sense (super fast) in regard to database query execution speed (super slow). Also, from my point of view, memory allocation is not a problem here.

**Comment by bherila** [comment]
Interpolation will require significantly more processing and caching will cause the generated objects to survive multiple GC generations. Even for the overhead of maintaining a dictionary of cache keys, it is not worth caching string concatenations IMHO.

**Comment by frankhommers** [comment]
@ahydrax, can you supply more code examples? How would that provider be implemented?

**Comment by frankhommers** [comment]
No response from @ahydrax, therefore I will close this issue as it's a really minor speed/memory improvement.
