### ISSUE TITLE
Could not place a lock on the resource

### ISSUE THREAD

**Issue by jenyayel** [frankhommers/Hangfire.PostgreSql#48]
This is related to #31. I have version 1.4.3 of Hangfire.PostgreSql.NetCore with 1.6.4 of Hangfire. I noticed that I keep getting this error and scheduled jobs are not executed until I cleanup `lock` table. This happens when application crashes while scheduled job being executed.

Now, I took a look at `PostgreSqlDistributedLock` and in different from `SqlServerDistributedLock` (which uses `sp_getapplock`) it use custom implementation of distributed lock, which on acquire lock writes in transaction new row into `lock` table and when lock released it deletes the row. Obviously, if application would crash when the row exists in DB, no one will release lock/delete row.

My question is, is it intentional not to maintain lock timeout (which may prevent those situation with application crash)?

**Comment by vytautask** [comment]
I think @frankhommers could better answer to your question. However, I am thinking that there could be a possibility of a job that could take a very long time (think - days) and that timeout would do real harm then.
Another interesting thing about this particular situation - crash. Why would that happen? Maybe you have some negative experiences about that? Could you elaborate on that?

**Comment by jenyayel** [comment]
@vytautask thanks for replying. I suggested the timeout only because this is how it is implemented in `SqlServerDistributedLock`. I'm also not 100% sure that this lock is hold for entire job execution, but only for the part where job is pulled from DB and scheduled. 

As for the crashing part, I cannot just ignore the fact the application can crash (it happens more often when you run in containers).

**Comment by frankhommers** [comment]
@jenyayel we should implement a lock timeout and clean up. I think the version it was based on didn't have any lock timeout functionality yet.

**Comment by jenyayel** [comment]
OK, thanks for clarifying. I'll try to find a time for PR, do you mind?

**Comment by jenyayel** [comment]
That's strange: I see that there is this  #44

**Comment by jenyayel** [comment]
I just discovered this #44 PR, which fixes the issue I was talking about. It is also marked for milestone 1.4.3. I have this version of Nuget, but DB schema version is 6 and there is also no column `acquired`. 😕

**Comment by bherila** [comment]
I think new nuget packages are needed... @frankhommers  ?

**Comment by vytautask** [comment]
@bherila #44 was definately included in 1.4.3 release. @jenyayel, are you sure you are using 1.4.3 version? Maybe there is something interesting in logs about not being able to upgrade DB?

**Comment by jenyayel** [comment]
This is from my project.json:
```
    "Hangfire.Core": "1.6.4",
    "Hangfire.PostgreSql.NetCore": "1.4.3",
    "Hangfire.AspNetCore": "1.6.4",
```
Deleted DB and created new one, the ran and here are logs:
```
DEFAULT_APPNAME Information: 0 : [09:32:49:416] [INF] Start installing Hangfire SQL objects...
DEFAULT_APPNAME Information: 0 : [09:32:50:054] [INF] Hangfire SQL objects installed.
```
Still the version is 6.

Went to dll in nuget and here it what it is contains:
![image](https://cloud.githubusercontent.com/assets/1775602/19848396/ec8bab5e-9f55-11e6-9012-7bcead37bdd1.png)

**Comment by vytautask** [comment]
Very interesting, however you are talking about NetCore version which was not released officially (yet) by us. You have some custom build of the library. Maybe you could try to update it yourself?
I will try to publish new versions of packages today as the generous maintainers fixed the tests.

**Comment by vytautask** [comment]
Please try new package from github. It is not uploaded to NuGet yet.

**Comment by jenyayel** [comment]
@vytautask thanks for answering, but this is even more confusing. 

First full what I have is obtained from [nuget.org feed]:(https://www.nuget.org/packages/Hangfire.PostgreSql/1.4.3):
![image](https://cloud.githubusercontent.com/assets/1775602/19854984/b140b466-9f7a-11e6-9388-c74101fe7845.png)

You may also notice that your package has dependency on .NETStandard, so why you mentioned that it is not released for .NET Core?

**Comment by topwik** [comment]
i still seeing a bunch of these errors pop up in my logs 
i'm currently using 1,4,4 of the repo titled postgres.hangfire.revised. Has that one been deprecated in favour of the frank hommers version?

  <package id="Hangfire.Core" version="1.6.6" targetFramework="net452" />
  <package id="Hangfire.Dashboard.Authorization" version="2.1.0" targetFramework="net452" />
  <package id="Hangfire.PostgreSql.Revised" version="1.4.4" targetFramework="net452" />

**Comment by bherila** [comment]
As far as I know, yes.

**Comment by vytautask** [comment]
@jenyayel the package you are describing (https://www.nuget.org/packages/Hangfire.PostgreSql.NetCore/) is definately not a part of our project and thus we can not and will not support it (unless the author zhong_zhaofeng will approve us).
I have sent a message to zhong asking for permissions to push to his package repo, however I do have low expectations of outcome :)

**Comment by jenyayel** [comment]
Wow, what a mess. I just now realized that this is totally different package.
