### ISSUE TITLE
Missing assembly reference error

### ISSUE THREAD

**Issue by dinesh64** [frankhommers/Hangfire.PostgreSql#50]
Install-Package : Could not install package 'Hangfire.PostgreSql 1.4.3'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any 
assembly references or content files that are compatible with that framework. For more information, contact the package author.
At line:1 char:1
- Install-Package Hangfire.PostgreSql -Version 1.4.3
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
  - FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand

**Comment by vytautask** [comment]
Maybe you are getting this error is because you are trying to install Hangfire.PostgreSql 1.4.3 into the project with older .net version (v4.0)?
Could you write some additional information about your setup? Like:
* .NET version your application is running on
* NuGet version

**Comment by vytautask** [comment]
Please try new package from github. It is not uploaded to NuGet yet.

**Comment by vytautask** [comment]
Is this still an issue?

**Comment by dinesh64** [comment]
Hi,
Sorry for late replay.  I clone the repository and build the DLL for .NETFramework,Version=v4.5 and its working. 

Thanks for your support.

**Comment by devdatta** [comment]
The issue is still there in the latest release. Please check.
