### ISSUE TITLE
Update psake scripts with core NuGet packages

### ISSUE THREAD

**Issue by vytautask** [frankhommers/Hangfire.PostgreSql#54]

**Comment by jenyayel** [comment]
I guess you can close this issue now. One last question, when are you going to upload Nuget with core support?

**Comment by jenyayel** [comment]
@vytautask ping

**Comment by ericgreenmix** [comment]
Yes! Lets get core support to nuget!

**Comment by githubperson** [comment]
Hi,
 Are you going to upload Nuget with core support?

**Comment by vytautask** [comment]
Sorry for late reply. Zhong did not respond to my request to add me to contributors on NetCore package in NuGet. That results that we have to change namespace/package name ("Hangfire.PostgreSql.NetCore") to some other one (because NetCore belong to Zhong now...).
Solutions:
a) change name to something else;
b) get in contact with Zhong (somehow) and resolve this issue (I've tried however was unsuccessful).

**Comment by githubperson** [comment]
It would be great if it’s possible.
Actually Hangfire.PostgreSql.NetCore 1.4.3 package is not the same as Hangfire.PostgreSql 1.4.3. It doesn’t contain a fix which was included in Hangfire.PostgreSql 1.4.3 -  Implemented distributed lock timeout (#44) (https://github.com/frankhommers/Hangfire.PostgreSql/issues/44)

**Comment by vytautask** [comment]
@githubperson you could use https://github.com/frankhommers/Hangfire.PostgreSql/releases/download/1.4.4/Hangfire.PostgreSql.NetCore.1.4.4.nupkg
@jenyayel could you, please, update project files to target that?

**Comment by jenyayel** [comment]
@vytautask  here you go #59 

Please note, that your build system relies on `nuspec`, thus the changes of targets were made there. I also bumped version and updated release notes.

**Comment by vytautask** [comment]
@jenyayel thank you very much

**Comment by vytautask** [comment]
@jenyayel please test with the new package from NuGet ;)

**Comment by githubperson** [comment]
Thank you very much guys! )
