### ISSUE TITLE
Rewrite some time-related tests

### ISSUE THREAD

**Issue by kanshi255** [frankhommers/Hangfire.PostgreSql#58]
Because of time difference with remote database server some tests (such as Hangfire.PostgreSql.Tests.PostgreSqlWriteOnlyTransactionFacts.ExpireJob_SetsJobExpirationData) are failing. It can also happen inconsistently due to some network lag.

**Comment by ahydrax** [comment]
I think these tests are intended to be run on development machine with properly prepared environment (installed database etc.). So there are no reasons to rewrite tests for using in various environments.

**Comment by vytautask** [comment]
@kanshi255, your pull requests are welcome. However, there really is no critical need for this.

**Comment by frankhommers** [comment]
@kanshi255: Using the database server for the time is as designed. So that multiple Hangfire servers will take the same date by using the database and won't have issues by have the Hangfire servers out of sync.
