### ISSUE TITLE
.NET Core support

### ISSUE THREAD

**Issue by adamhathcock** [frankhommers/Hangfire.PostgreSql#60]
I noticed there is a separate package for this for .NET Core support.

Why is this?  Do you guys need help with your project.json for supporting .NET 4.5.2 and .NET Core 1.1?

**Comment by jenyayel** [comment]
The .NET Core package is not related to this repository. I had this confusion as well here #48. `Hangfire.PostgreSql.NetCore` and `Hangfire.PostgreSql` have different owners.

**Comment by adamhathcock** [comment]
Looks like it should be the same.  It should be possible.  I can give it a go in a pull request.

**Comment by adamhathcock** [comment]
What's the status of the pull request?  I think I solved the issues.  Just interested in the schedule of the next release.

I'd like to use this library over a Redis one for permanent storage.

**Comment by adamhathcock** [comment]
Oops, shouldn't use my phone on github

**Comment by adamhathcock** [comment]
I updated my branch.  I've also published a forked package as I needed to target `netstandard`

Let me know what's the thoughts on my PR.  Thanks!

**Comment by ericgreenmix** [comment]
Now we just need a release!

**Comment by ericgreenmix** [comment]
Where are we with pushing to nuget? Really looking forward to having this out.

**Comment by vytautask** [comment]
I hope to do this in a couple of days.

**Comment by vytautask** [comment]
Many thanks goes to @adamhathcock! You made this possible!
Release was made 🎉  ;)
