### ISSUE TITLE
License

### ISSUE THREAD

**Issue by adamhathcock** [frankhommers/Hangfire.PostgreSql#62]
Is the license for this really GPL 3?  So if I use this then I have to open source my entire cloud app?

Hangfire itself is just LGPL which means I have to keep my modifications open (totally fine with) but I can use in my app that is closed.

**Comment by vytautask** [comment]
Are you sure? Because according to https://tldrlegal.com/license/gnu-lesser-general-public-license-v3-(lgpl-3), you must disclose source code either way.
However, if this is an issue for you, we could discuss it further with @frankhommers

**Comment by adamhathcock** [comment]
I have to disclose source if I change the LGPL library but it doesn't force me to disclose any application that uses the LGPL library.

GPL is viral in that it forces me to disclose my application if I use any GPL code.

If this stays GPL, I'll be forced to write my own Postgres code or use a separate backend just for HangFire.

**Comment by adamhathcock** [comment]
in your link, this is the key phrase:
```
Derivatives works (including modifications or anything statically linked to the library) can only be redistributed under LGPL, but applications that use the library don't have to be.
```

**Comment by vytautask** [comment]
@adamhathcock understood.
@frankhommers is it feasible (and possible) to change licencing model of Hangfire.PostgreSql?

**Comment by adamhathcock** [comment]
Really need to know this.  I think a lot of other people using this library don't realize it's labeled as GPLv3.

LGPL (or better yet Apache/MIT) would be what I need.  Thanks @frankhommers

**Comment by frankhommers** [comment]
This is what the readme and license shows:

Hangfire.PostgreSql is free software: you can redistribute it and/or modify it under the terms of the GNU **L**esser **G**eneral **P**ublic **L**icense as published by the Free Software Foundation, either version 3 of the License, or any later version.

Where does it say GPL according to you?

**Comment by adamhathcock** [comment]
On the github page, next to contributors tab.  Maybe there isnt a LGPL or maybe it's just according to me.

**Comment by frankhommers** [comment]
Ah seems like GitHub is detecting it wrong. Let see if I can fix it.

**Comment by frankhommers** [comment]
Now it's LGPL3 everywhere. GitHub was displaying it wrong.

**Comment by adamhathcock** [comment]
Thank you for clearing up the confusion.
