### ISSUE TITLE
Problem with max pool connections

### ISSUE THREAD

**Issue by Nickholas** [frankhommers/Hangfire.PostgreSql#64]
I dont know why but when i try to run my web application using Hangfire.PostgreSql i get the same error:
`"Unable to connect to PostgreSQL server: FATAL: connection limit exceeded for non-superusers"`. I have read the postgresql.conf i and have the default vale : max 100 connections so i dont think that this is the problemm. Here is my initialization code in startup.cs:

app.UseHangfireServer(new BackgroundJobServerOptions(), new Hangfire.PostgreSql.PostgreSqlStorage("DefaultConnection"));

> I have found the error. It was because when i installed your library using nuget package, it updates by itself my old version of npgsql 3.2.1 and it breaks my code because i was using 3.0.1. Now, i am thinking to update all my old code into the newest version before traying to use your library again.

Thank you very much

**Comment by vytautask** [comment]
Could you try to set max connections to 1000 for testing purposes?
Is this still an issue?

**Comment by frankhommers** [comment]
No response. Closing.
