### ISSUE TITLE
Job queue name length

### ISSUE THREAD

**Issue by Z1ni** [frankhommers/Hangfire.PostgreSql#71]
Queue name length is now hardcoded at 20 characters, which is pretty short. Hangfire.SqlServer fixed this back in 2015 by bumping it up to 100. I see no problem doing the same thing here.

Relevant Hangfire issue: HangfireIO/Hangfire/issues/369

**Comment by frankhommers** [comment]
I think we need to change all varchar columns to text. Because there is no performance hit, see the tip here: https://www.postgresql.org/docs/9.1/static/datatype-character.html

What do you think, @vytautask ?

**Comment by vytautask** [comment]
Good idea. Though I feel that code overview (to ensure that we __never__ select by name) + testing with lot's of data should be done first as there are lots of folks who uses our package in production systems.

**Comment by zhiyuanzhang-unai** [comment]
I have created a PR #95 to fix this. Please review.

**Comment by zhiyuanzhang-unai** [comment]
@frankhommers this is resolved. Please close this issue

**Comment by vytautask** [comment]
Released with version 1.5.0
