### ISSUE TITLE
Hangfire.PostgreSql and .net core

### ISSUE THREAD

**Issue by SkogDev** [frankhommers/Hangfire.PostgreSql#72]
Hi, 

I've been trying to implement Hangfire.PostgreSql, with hangfire 1.6.14 and .net core. This process have been most troublesome, and I'm now wondering if anyone else have managed to get this to work.

Thanks,

**Comment by vytautask** [comment]
I see no reason this would be a problem. Will look into that.

**Comment by vytautask** [comment]
Just tried updating hangfire and running tests. Everything works as expected. Maybe you could elaborate a little bit more? What errors/problems are you having?

**Comment by SkogDev** [comment]
@vytautask The problem is more setup-related. I can't seem to get it working, while following the readme. A short setup instruction for .net core would have been preferable.

**Comment by vytautask** [comment]
🎉 I've updated Readme as well as [created a sample project for aspnet core]( https://github.com/frankhommers/Hangfire.PostgreSql/releases/download/1.4.8.1/aspnetcore_hangfire_sample.zip). Thanks for your input!

**Comment by SkogDev** [comment]
@vytautask Thank you!
