### ISSUE TITLE
Could not release a lock on the resource

### ISSUE THREAD

**Issue by mantasaudickas** [frankhommers/Hangfire.PostgreSql#75]
Hi,

I have a long running job, which timeouts after 30minutes with an exception. Basically I cannot run longer jobs. Maybe some setting is missing? Thats the only information I can see in Hangfire dashboard:

> Hangfire.PostgreSql.PostgreSqlDistributedLockException
> Could not release a lock on the resource 'HangFire:IDataStreamService.RebuildElasticSearchIndexes'. Lock does not exists.
> Hangfire.PostgreSql.PostgreSqlDistributedLockException: Could not release a lock on the resource 'HangFire:IPortfolioService.RebuildPortfolioSearchIndexes'. Lock does not exists.
   at Hangfire.PostgreSql.PostgreSqlDistributedLock.Dispose()
   at Hangfire.Server.BackgroundJobPerformer.InvokePerformFilter(IServerFilter filter, PerformingContext preContext, Func`1 continuation)

**Comment by mantasaudickas** [comment]
I use Version=1.4.8.0.
My settings are these:
```
var storage = new PostgreSqlStorage(connectionString, new PostgreSqlStorageOptions
{
   QueuePollInterval = TimeSpan.FromSeconds(30),
   InvisibilityTimeout = TimeSpan.FromHours(1)
});
GlobalConfiguration.Configuration.UseActivator(new LightInjectJobActivator());
GlobalConfiguration.Configuration.UseStorage(storage);

var options = new BackgroundJobServerOptions
{
    Activator = new LightInjectJobActivator(),
    Queues = new[] {QueueNames.Critical, QueueNames.Important, QueueNames.Default, QueueNames.Email},
    HeartbeatInterval = TimeSpan.FromMinutes(1),
    SchedulePollingInterval = TimeSpan.FromSeconds(30),
    WorkerCount = 5
};
```

**Comment by frankhommers** [comment]
Could you put a Thread.Sleep(300000) in your task and then verify just after it started if there is a correct entry in table lock?

**Comment by ahydrax** [comment]
Hi @mantasaudickas ,
If your jobs are long-running processes then consider to change [this](https://github.com/frankhommers/Hangfire.PostgreSql/blob/master/src/Hangfire.PostgreSql/PostgreSqlStorageOptions.cs#L37) setting. For your case you can put 1 hour.

**Comment by mantasaudickas** [comment]
Yes I have these settings set.
            var storage = new PostgreSqlStorage(connectionString, new PostgreSqlStorageOptions
            {
                QueuePollInterval = TimeSpan.FromSeconds(30),
                InvisibilityTimeout = TimeSpan.FromHours(2),
                DistributedLockTimeout = TimeSpan.FromHours(2)
            });

I think it was already there when error happened. But in the last half of the year I did not received any related error. So I guess issue can be closed.
