### ISSUE TITLE
Why is Hangfire.Postgres not supporting Npgsql Enlist

### ISSUE THREAD

**Issue by shankbond** [frankhommers/Hangfire.PostgreSql#76]
Hi,

Was curious as to why Npgsql Enlist is not supported. As stated in [PostgreSqlStorage](https://github.com/frankhommers/Hangfire.PostgreSql/blob/f2a6dca2407bda4db0637d56ed62444e7432f7d7/src/Hangfire.PostgreSql/PostgreSqlStorage.cs#L116) but latest [Npgsql](http://www.npgsql.org/doc/transactions.html) says that it supports TransactionScope.

**Comment by frankhommers** [comment]
It seems that this was fixed in late 2016, beginning of 2017 for Npgsql.

I started Hangfire.PostgreSql way before that. After my start @vytautask took most of the work over,  but we didn't take notice of the change in Npgsql. So it probably can be done now, we welcome PR for that ;-)

**Comment by frankhommers** [comment]
Closed for inactivity.
