### ISSUE TITLE
Operation in Progress Exception

### ISSUE THREAD

**Issue by BrutalSimplicity** [frankhommers/Hangfire.PostgreSql#77]
I'm using this awesome nuget package for a project to run a background service in a web service. One of the background jobs updates several other tables in the same database. The code that does this disposes of the connection object after each call. The problem I have is that I keep receiving exceptions about "Operation in Progress" that come from Hangfire.PostgreSql, and am wondering if there may be something I need to configure or use to avoid this.

Here are some screenshots of the exception:
![image](https://user-images.githubusercontent.com/5298126/30978176-691b390c-a43f-11e7-9191-c6c8a03a85b9.png)

![image](https://user-images.githubusercontent.com/5298126/30978196-73f40264-a43f-11e7-9595-9e6c976d09ee.png)

They are two different exceptions, but seem to be related. I'm wondering if this may not even be an issue with Hangfire.PostgreSql, but with NPGSQL. I see this [PR](https://github.com/npgsql/npgsql/pull/1610), which talks about two issues that sound a bit like this, but can't tell if it has been released yet.

Do you all have any ideas on ways to mitigate this?

Let me know if you need additional detail.

**Comment by vytautask** [comment]
Hi,
As I understand, your project is using the same database as the Hangfire. Does the problem remain if you do not dispose of connections?

P. S.
Regarding that PR in Npgsql, you could just update npgsql on your project and see what happens :)

**Comment by frankhommers** [comment]
Avoid that your code and hangfire's connection are the same. One way to do this is add the "Application Name" element to your connection string and append "- Hangfire.PostgreSQL" to the one used by Hangfire.
