### ISSUE TITLE
"Timeout while getting a connection from pool." postgres

### ISSUE THREAD

**Issue by gabrieligbastos** [frankhommers/Hangfire.PostgreSql#8]
Hi,

I'm new to Hangfire, so probably I'm messing up somewhere. I have the Hangfire configured like in: https://github.com/HangfireIO/Hangfire#installation

but instead of:

    config.UseSqlServerStorage("<connection string or its name>");

I have:

    config.UsePostgreSqlStorage("Server=127.0.0.1;Port=5432;User Id=postgres;Password=pwd;Database=Hangfire");

So I created an Hangfire Database in my DB.

And then, I'm building and running my project. It is ok. Creating all tables in Hangfire DB at my postgres. It is working great.

But then, when I'm trying:

      BackgroundJob.Enqueue(() => HubService.SendPushNotificationToUsers(threadParticipants,  messageApi.SenderId, messageApi.SenderName, messageApi.ThreadId, messageApi.Content));

I'm receiving an exception with the InnerMessage: 

     "Timeout while getting a connection from pool." postgres

Am I missing something?

Thanks in regards,

**Comment by frankhommers** [comment]
Can you post the StackTrace?

**Comment by gabrieligbastos** [comment]
For sure, here is the exception:

       [Hangfire.Client.CreateJobFailedException] = {"Job creation process has bee failed. See inner exception for details"}

       in Hangfire.BackgroundJobClient.Create(Job job, IState state)
       in Hangfire.BackgroundJobClientExtensions.Enqueue(IBackgroundJobClient client, Expression`1 methodCall)
       in Chat.Controllers.ApiControllers.MessageController.<SendMessage>d__11.MoveNext() at \\psf\home\Documents\Gabriel Docs\Development\Chat\Chat\Controllers\ApiControllers\MessageController.cs:line 121

And the inner exception is:

       InnerException = {"Timeout while getting a connection from pool."}

       in Npgsql.NpgsqlConnectorPool.RequestConnector(NpgsqlConnection Connection)
       in Npgsql.NpgsqlConnection.Open()
       in Hangfire.PostgreSql.PostgreSqlStorage.GetConnection()
       in Hangfire.BackgroundJobClient.Create(Job job, IState state)

Any clue of what is the problem?
I'm using my MacBook Pro 15 Retina, using Parallels Desktop 10 to virtualize a Windows 8.1 with Visual Studio 2013 Community Edition.

Thanks in regards,

**Comment by gabrieligbastos** [comment]
Any idea? Am I missing something ?

**Comment by frankhommers** [comment]
No idea (yet). I would start with investigating by setting Pooling=false in the ConnectionString and see what happens then. Is your PostgreSQL server virtualized as well?

**Comment by gabrieligbastos** [comment]
If I set pooling to false, then it works. Not throwing exception any more, and adding the job at the database.
But it is not running the job. Should I do something more?

**Comment by gabrieligbastos** [comment]
Actually, I'm using FormsAuthentication, so when I try http://localUrl/localProject/hangfire, it is not appearing the dashboard but the login page instead.

How should I proceed?

**Comment by gabrieligbastos** [comment]
Already figured it out. Thanks very much Frank!

**Comment by frankhommers** [comment]
First try to get the server working. Did you invoke UseServer? And after that, if you Pause the Debugging Session, do you see the Thread named "Server Core"? If not you might want to check out the Hangfire Getting Started documentation.

**Comment by frankhommers** [comment]
What did you change? So other people can learn..

**Comment by gabrieligbastos** [comment]
For the server to work, I turn off pooling in DB like you said with:

      "Server=ipAddress;Port=port;User Id=username;Password=password;Database=database;Protocol=3;Pooling=false;"

Not sure, if it is gonna be a problem for me further.

Then, I was not getting the dashboard because of FormsAuthentication. Reading the Hangfire documentation found that this would solve:

     config.UseAuthorizationFilters();

Finally, the problem that was causing the jobs to be scheduled and saved at database but not being executed was at dashboard. Over there, i found it was because of my IoC. So, I installed the Hangfire.Unity package and added the Activator at the Startup.

     config.UseUnityActivator(container);

Finally, got all working! Thanks very much for your help ;)

**Comment by SergeyMirvoda** [comment]
Same for me.
Only works when pooling is off.

**Comment by bogdanvarlamov** [comment]
I am currently using version 1.3.4.0 from NuGet and I also had to modify my connection string to specify Pooling=false;
