### ISSUE TITLE
Could downgrade the version of Newtonsoft.Json to 10.0.1?

### ISSUE THREAD

**Issue by LeafDuan** [frankhommers/Hangfire.PostgreSql#83]
Hi,

Could downgrade the version of Newtonsoft.Json to 10.0.1？

Because, the (asp) net core 2.0 mainly use the version of Newtonsoft.Json is 10.0.1,
and the hangfire.core use the version  of Newtonsoft.Json is 9.0.1,
so our projects and libraries are using the version  of Newtonsoft.Json is 10.0.1.

Since the Hangfire.PostgreSql use the the version  of Newtonsoft.Json is 10.0.2, 
and forcing upgrade the version of Newtonsoft.Json in othre libraries to 10.0.2,
but which is not expected.

Thanks
Leaf

**Comment by bherila** [comment]
I agree, there does not seem to be any advantage to this newer version of Newtonsoft.Json and also have been having issues with the newer versions.

**Comment by frankhommers** [comment]
Sure, send us a PR.

**Comment by vytautask** [comment]
Released with version 1.5.0
