### ISSUE TITLE
Error on starup project - PostgreSQL 9.0

### ISSUE THREAD

**Issue by evandrofuhr** [frankhommers/Hangfire.PostgreSql#88]
Hi, I'm trying to start my app on the legacy postgresql 9.0 server, but I have many errors on starup, because 9.0 does not give support to "IF NOT EXISTS" on "CREATE TABLE". It's only available in 9.1 or higher. It's possible to update project in future ?

Thanks

**Comment by frankhommers** [comment]
I don't really see the need to support older PostgreSQL versions. For now you can create the model itself by running install.v*.sql by hand and correcting the errors by hand too.
