### ISSUE TITLE
Upgrade npgsql to 4.0.2

### ISSUE THREAD

**Issue by jameskimsca** [frankhommers/Hangfire.PostgreSql#89]
According to the release notes, the 4.0 release has major performance boost:
http://www.npgsql.org/doc/release-notes/4.0.html

Need a new version of hangfire.postgresql that uses the new version and also supports .net core 2.0/2.1.

**Comment by frankhommers** [comment]
Sure send us a PR.

**Comment by vytautask** [comment]
Released with version 1.5.0
