### ISSUE TITLE
Idle Hangfire connections exhaust the connection pool

### ISSUE THREAD

**Issue by ilya-chumakov** [frankhommers/Hangfire.PostgreSql#90]
Our .NET Core Hangfire server uses a PostgreSQL db. There is a single recurring job executing every minute on the server. Checking `SELECT * FROM pg_stat_activity;` output I see the number of idle connections steadily growing until it reaches the PostgreSQL server limit and thus blocks any further connections to the entire db server.
It's never happened before with low-frequent jobs. It doesn't happen with another apps sharing the same db server.

How to fix this Hangfire behavior? 

`pg_stat_activity` filtered output:

datname | backend_start | query_start | state_change | state | query
---------- | --------------- | ------------ | --------------- | ----- | ------
<hangfire_db_user> | 2018-07-20 13:12:13 | 2018-07-20 13:59:42 | 2018-07-20 13:59:42 | idle | COMMIT

The server details:

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="HangFire" Version="1.6.19" />
    <PackageReference Include="Hangfire.PostgreSql" Version="1.4.8.2" />
  </ItemGroup>
</Project>
```

**Comment by ahydrax** [comment]
Hi @ilya-chumakov , could you try to test the same scenario with my package (https://github.com/ahydrax/Hangfire.PostgreSql)?

**Comment by ilya-chumakov** [comment]
3. Limited `statement_timeout` to 15s 
Result: no effect.

4. Tried https://github.com/ahydrax/Hangfire.PostgreSql . Unfortunately, no effect too, @ahydrax 

A funny thing: a Hangfire server can produce even 500 idle connections, but it still works successfully when the connection limit is set to 10 on PostgreSQL server (the `max_connections` setting).

**Comment by ahydrax** [comment]
@ilya-chumakov can you also try latest beta version of my package with Pooling=true and Max Connections parameters?

**Comment by ilya-chumakov** [comment]
I've figured out what is wrong. Our code has some custom logic writing into Hangfire `hash` table (we had to invent our way to synchronize different jobs because Hangfire doesn't have it out-of-the-box and I would be happy to share the knowledge if someone has solved the same task).
So, we call `JobStorage.Current.GetConnection()` method to get a connection to read/write data. I would never expect this method creates **new connections** if I didn't check the sources. It seems the right pattern to use it is:

    using (var connection = JobStorage.Current.GetConnection())
    {
        //do something with db
    }

Once we've started explicitly disposing the connections, Hangfire is no longer dries out the connection pool. Moreover, it used to do it from the client side, not from the server one.

P.S., aligning Hangfire pool limits with your Postgres `max_connections` setting can be quite helpful, especially if its db is on a shared server. Keep in mind that every Hangfire client has his own connection pool getting connections from a single Postgres pool.

**Comment by frankhommers** [comment]
I guess this is fixed by your own code now?

**Comment by damikun** [comment]
If I call multiple times GetConnection()... it can be very bad... I allso comes to this issue after using hangfire internal classes... Isn't it better to have connection manager class (Fascade) to handle only one connection and:

- close connection if no request is pending for example +5s
- keep it open and pass all request over it ? 

Equal is done by EFCore... It never open multiple connections use once by default...

Or the idea was that devs make this connection manager by themselves?
