### ISSUE TITLE
Update to 1.6.20?

### ISSUE THREAD

**Issue by burodevelopment** [frankhommers/Hangfire.PostgreSql#97]
Anyone fixing the current build and upgrade to Hangfire 1.6.20 soon?

I have one project depending on this ;-)

**Comment by vytautask** [comment]
Build is not actually failing - just AppVeyor integration seems to be
broken :)

**Comment by vytautask** [comment]
Also, Hangfire version was updated with
https://github.com/frankhommers/Hangfire.PostgreSql/pull/94 ...
